popcodeorg/popcode

package.json, src/validations/css.js, src/validations/css/css.js, src/validations/css/prettycss.js
Not complete—would like to support many more PrettyCSS warnings, and
there is some good stuff in csslint as well. However better to have the
basic validations in place and move on for now.
N.B. using both `css` and `PrettyCSS` because the former has better/more
specific error catching in a handful of important situations (most
notably when there’s no closing curly brace). Might need to do some
deduplication/prioritization of the errors generated.
Fixes #4
=> CSS validations

src/config.js, src/editor.jsx, src/validations/html.js, src/validations/html/htmllint.js, static/index.html
Use `htmllint` to point out errors in HTML markup.
Unfortunately, while `htmllint` can provide a lot of useful output, it doesn't do the most basic and important validation: correct syntax.
Other things `htmllint` doesn't do that I'd like to:
* Catch invalid tag nesting
* Point out bad indentation
=> HTMLLint validation

package.json
Needed by htmllint but not specified as a dependency, apparently
=> Add bulkify dependency

README.md, src/components/editor.jsx, src/components/output.jsx, src/components/preview.jsx, src/components/toolbar.jsx, src/components/workspace.jsx, src/config.js, src/services/storage.js, src/validations/javascript.js, static/application.css, static/index.html, static/locales/en/translation.json
Possible to toggle libraries on and off and have them included in the page markup.
To do:
Follow ups:
=> Add libraries

package.json
Server response is delayed until JS recompiles; also introduces live reloading
=> Use budo for recompilation in dev

src/services/Storage.js
Prevents storage from being in an invalid state where there is a key in the list referring to a project that is not there.
=> Wait for project to finish saving before updating key list

.eslintrc, README.md, package.json, src/validations/html.js, src/validations/html/htmllint.js, src/validations/html/slowparse.js, static/locales/en/translation.json
[Slowparse](https://github.com/mozilla/slowparse) is an HTML parsing library that is specifically designed to give good error feedback. Fills a big hole in our current HTML validation game.
Slowparse also does CSS and is probably worth integrating into CSS validation at some point, but current validation for CSS is reasonably comprehensive so it’s not a high priority right now.
=> Use slowparse for HTML problem detection

.travis.yml, package.json, src/actions/index.js, src/components/Output.jsx, src/components/Preview.jsx, src/components/Workspace.jsx, src/reducers/index.js, src/reducers/runtimeErrors.js, src/util/generatePreview.js
Runtime errors in JavaScript code are now propagated back to the environment via a postmessage. Currently runtime errors are only displayed as annotations in the editor; they don’t populate the error list because in the case of a runtime error we don’t want to replace the whole preview window. Instead, I’ll follow up with functionality to slide up an error list at the bottom of the preview in the case of a runtime error.
Another followup is to “translate” runtime errors into student-friendly messages. Unfortunately as far as I know there’s no better option here than simply making a bunch of regular expressions to map the matrix of error types + commonly used browsers.
=> Catch and report runtime errors

package.json, src/components/Preview.jsx
Use TextEncoder polyfill and base64 polyfill to get multibyte character-friendly base64 encodings.
=> More robust base64 encoding for popout

src/validations/html.js, src/validations/html/htmllint.js
* Don’t report an error if HTML begins with a line of whitespace
* Don’t report an invalid tag error if there is a tag before the DOCTYPE (this is already reported as a DOCTYPE error)
=> Fixes for incorrect HTML errors

src/components/ErrorList.jsx, src/components/Output.jsx, src/components/Workspace.jsx, src/reducers/runtimeErrors.js, static/application.css
If a runtime error occurs, we don’t want to completely cover the preview like we do for a compilation error. Instead, slide up a list of errors docked to the bottom of the preview column.
Also changes the toolbar/menu to be absolutely positioned, which is better for the layout.
=> Show runtime error list docked to the bottom of the preview

static/application.css
So that it completely covers page (although the page should really shrink to fit)
=> Background color for error list

locales/en/translation.json, src/components/Preview.jsx, src/util/normalizeError.js, static/application.css
Basically just covers TypeErrors caused by:
* Calling something as a function that isn’t a function
* Attempting to access a property of something that’s null or undefined
Obviously that is fairly narrow, but my intuition is that it also covers a solid majority of the actual runtime errors students would see in the wild.
Currently translates errors for Chrome, Safari, and Firefox.
=> Friendly translations for runtime errors

src/components/Preview.jsx
Fixes bug where browser assumes a different encoding and renders multibyte characters incorrectly.
=> Specify encoding in data URL for pop out

src/components/Preview.jsx, src/components/PreviewFrame.jsx
Ref callback does not get called every time the component updates, so we were not live-updating the preview when the project itself changed. So, ref callback now saves the frame as a property on the component, and then we listen for `componentDidUpdate` and update the frame contents if the project itself has changed.
Extracted a `PreviewFrame` component to deal with the details of rendering the frame and receiving messages.
=> Write out frame contents in Safari/IE when props have changed

src/components/ErrorItem.jsx, static/application.css
Instead of showing “Line X:”, put it in a little box with rounded corners.
=> Nicer(?) styling for line numbers in error list

src/components/LibraryPicker.jsx
This is no longer supported in lodash 4
=> Don’t pass bind argument to lodash map

src/util/generatePreview.js
Fixes preview generation when library enabled
=> Add missing `this` binding

.babelrc, .eslintrc, .travis.yml, gulpfile.js, package.json, src/config.js
* Sets `NODE_ENV` to production when building in Travis
* Browserify bundle function is reusable, returns a promise which can just be return value of gulp task
* Switch to Babel for JSX compilation
* Output full paths for Browserify bundle in development for disc compatibility
* Don’t use browserify-incremental when building for production
=> Improvements to the build process

src/util/generatePreview.js
When rendering preview, don’t assume that `document.documentElement`, `document.head`, and `document.body` exist—if the HTML input to the preview is malformed, they may not. So, check to see if they exist, and create them if not.
“But why would we be rendering a preview with malformed HTML?”, you may wonder. As it happens, any time the user types into the editor, the error state of the project is reset. Then validations are run, and then the error state is flipped back on based on validations. This is not great, but best tackled separately.
=> Ensure the existence of <html>, <head> and <body> elements

.travis.yml, package.json, src/actions/__tests__/index-test.js, src/reducers/__tests__/currentProject-test.js, src/reducers/__tests__/errors-test.js, src/reducers/__tests__/projects-test.js
This is the officially supported jest plugin for ES2015, and works better for module mocking.
Unfortunately `jasmine-pit` doesn’t seem to respect `this` in the latest version of `jest`, so I had to change a bunch of stuff to use lexical variables instead.
=> Use babel-jest rather than jest-babel-preprocessor

src/components/PreviewFrame.jsx
Important since it uses an ES6-style export
=> Use ES6-style import for sourceDelimiter

src/actions/index.js
Fixes debounce behavior (should continue waiting as long as you are still typing)
=> Construct debounced function only once

package.json, src/actions/index.js, src/components/Workspace.jsx, src/reducers/projects.js, src/services/Gists.js
When the `Workspace` bootstraps, it checks the query string for a `gist` parameter. If it finds one, this is passed to the `bootstrap` action, which will load the gist as the current project if an ID is present.
Also adds a nice bit of logic to the `projects` reducer which ensures we won’t hold on to an untouched project when switching away from it.
=> Import from gist

src/components/Editor.jsx
Unfortunately, this will also disable smart indenting of HTML
(but it won't disable smart indenting of CSS or JS).
There is no fine-grained way of doing this in the version of
brace that we're using. We have to enable/disable ALL behaviours
=> Don't autoclose HTML tags

src/actions/index.js, src/services/Gists.js
When we export a gist, immediately update the description to contain an import URL for the gist. We have to do this with an update because the import URL contains an ID, and we don’t know the ID until we create it.
Unfortunately it’s not possible to update anonymously, so this functionality only works if you’re logged in.
=> Update exported gist with import URL

src/validations/html/slowparse.js
When there's an unterminated open tag, the next tag is
interpreted as an attribute name. This triggers an
additional HTML lint error because "<" is not a lower
case character.
We're suppressing this error to make it less
confusing for students.
=> Suppress lower-case-attribute-name error

package.json, src/validations/html/htmllint.js
E.g., the input `<a>text</p>` will cause the `htmllint` promise to throw an uncaught promise error, which appears to be an internal bug.
If this happens, just return an empty list of errors (slowparse will catch it).
=> Catch uncaught errors in htmllint

src/css/application.css
=> Make page-level elements explicitly 100% height

package.json, src/application.js, src/components/Application.jsx, src/config.js, src/util/Bugsnag.js
Error reporting from the client side. Particularly interesting: we can attach arbitrary payloads to the error, so we send over the current user information as well as the contents of the current project.
=> Set up Bugsnag

src/reducers/projects.js
In particular, correctly sets `enabledLibraries` to a `Set` rather than a `List`.
=> Use projectToImmutable to consume imported project

locales/en.json, src/validations/javascript/esprima.js, src/validations/javascript/jshint.js
* Unexpected end of input can result in an uncaught error from jshint; catch it
* Also catch the "Unexpected end of input" error from esprima and surface it
* While you’re in there, just import jshint using `as` so it’s not upcase
=> Deal with unexpected end of input

src/components/Editor.jsx
For some reason, this requires resizing the editor after we’re done setting it up; otherwise, the sizes are out of whack.
=> Enable wrapping mode for editors

src/components/Preview.jsx, src/util/generatePreview.js
Also introduces options to preview generation—that way we can generate a straightforward preview for the pop-out, but add extra stuff (also error propagation) to the inline preview.
=> Add base tag to target top on links in preview

src/actions/index.js
Otherwise we‘ll blow it away if you subsequently log in without modifying anything.
=> Immediately add a timestamp to imported project

src/components/Editor.jsx
When the user changes projects or creates a new project, we create a new ACE session. However, using `new ace.EditSession()` gives it a blank undo manager, for some reason. `ace.createEditSession()` does basically the same thing, except it also sets up a real undo manager. Switch to using that.
=> Fix undo behavior

.projections.json, locales/en.json, src/validations/Validator.js, src/validations/css/css.js, src/validations/css/prettycss.js
* CSS input that ends with a comma causes PrettyCSS to throw an uncaught error. Catch uncaught errors.
* The same input generates a usable lint error from `css`. Map it.
=> Fix uncaught error on invalid CSS input; add real error

.eslintrc, src/components/Application.jsx, src/components/Dashboard.jsx, src/components/Editor.jsx, src/components/ErrorItem.jsx, src/components/ErrorList.jsx, src/components/ErrorSublist.jsx, src/components/LibraryPicker.jsx, src/components/LibraryPickerItem.jsx, src/components/Output.jsx, src/components/Preview.jsx, src/components/PreviewFrame.jsx, src/components/ProjectList.jsx, src/components/Sidebar.jsx, src/components/Workspace.jsx
Added a bunch of react-eslint rules, and then patched the code to follow them.
Two particularly good ones:
* Ban the use of `bind()` in callback props (this is a performance issue)
* Use stateless components where practical (could do more, but right now just converted the ones that are nothing more than a `render` function). This is a performance enhancement
=> Stricter React linting

locales/en.json, src/validations/javascript/esprima.js
Handles things like:
```javascript
var o = {a: 1 b: 2};
var a b;
```
=> Catch unexpected token errors

src/actions/index.js, src/components/Editor.jsx, src/components/ErrorList.jsx, src/components/ErrorSublist.jsx, src/components/Output.jsx, src/components/Workspace.jsx, src/reducers/errors.js
When a project source changes, the first thing that is dispatched is a change to the project state. Previously, this would unconditionally trigger a preview render cycle, since the error store would clear error state when validation began.
Now, we have an explicit idea of error state: `passed`, `failed`, or `validating`. The latter state is invoked as soon as an action results in a change to source code whose validity is not known. The explicit `VALIDATING_SOURCE` action is removed.
As a result, the preview is only rendered when the current source has been positively identified as valid.
This is particularly important for situations in which students have the console open; previously editing JavaScript with the console open would yield a flood of console errors. Also, rendering the …
=> Prevent preview from ever rendering invalid code

src/components/Output.jsx, src/components/Preview.jsx, src/components/PreviewFrame.jsx, src/css/application.css
Previously a runtime error would continue to be displayed even after being resolved. This is because the `PreviewFrame` only sent an `onFrameWillRefresh` event when it received new props; *not* when it initially mounted/was rendered. However, because of the three-phase error state, each keystroke resulted in the `PreviewFrame` at least briefly unmounting while validation was underway. So, the frame never updated; it was always torn down and rebuilt.
Two changes, either of which alone would solve the problem, but both of which seem like good changes to the code:
* `PreviewFrame` emits a frame refresh signal any time it flushes the contents of the frame (including when it is first mounted). This seems semantically correct
* `Preview` now always renders the `PreviewFrame`, but it knows …
=> Fix sticky runtime errors

locales/en.json, src/config/libraries.js, src/validations/javascript/jshint.js
E.g. if you try to use `$` but haven’t enabled jQuery, the error message will specifically suggest enabling jQuery, rather than a generic undefined variable message.
=> More descriptive error messages when using an undefined library global

src/components/Editor.jsx, src/components/Workspace.jsx
The ACE editor needs to be explicitly told when its container has changed in size. Previously we have been relying on a pretty clunky mechanism of just firing a resize when you focus the editor; however, this leads to noticeably bad behavior in a couple of cases:
* When the entire browser window is resized
* When you minimize or maximize one of the language editors
In both of these cases, the editor is visibly the wrong size until you actually focus it.
This update fixes both problems by adding a window resize event handler, and also making the editor component aware when its proportion of the overall editor column has changed, so that in both cases it can resize the editor itself.
=> Smarter editor resizing

src/components/Sidebar.jsx, src/css/application.css
“Cross-browser” meaning, of course, “for browsers that aren’t Chrome”.
Specifically:
* Fixes hugely oversized arrow in sidebar on Firefox
* Fixes incorrectly positioned wordmark in sidebar on Safari
* Fixes crowded sidebar in narrow viewports on Safari
=> Cross-browser CSS fixes

bower.json, gulpfile.babel.js, src/css/application.css
Ensure we serve up all the appropriate formats; also serving fonts separately allows the browser to keep them cached basically forever.
=> Serve fonts from our assets

src/css/application.css
To signal to the browser that it needs to load that font
=> Explicitly add a font-family declaration for editors

src/css/application.css
Was using `auto` flex basis before, which means “to fit your content”, which is not appropriate here (the editor should resize to fit its container, not vice versa). Switch to 100% flex basis, and remove flex-grow while we’re at it (since it shouldn’t grow to more than 100%).
Fixes issue where many pageloads yield oddly-sized editors.
=> Ensure editors are the same size

locales/en.json, npm-shrinkwrap.json, package.json, src/components/Application.jsx, src/components/BrowserError.jsx, src/css/application.css
Instead of loading the environment, just show an error message if the user’s browser isn’t supported (specifically, is known to lack a feature Popcode needs).
=> Error message if browser isn’t supported

npm-shrinkwrap.json, package.json, spec/examples/validations/css.spec.js
Points to a fork of PrettyCSS that I just patched to support Flexbox.
Currently only supports:
```css
display: flex;
flex-grow: 1;
flex-shrink: 0;
flex-basis: auto;
flex: 1 0 auto;
```
=> Basic support for flexbox

spec/examples/validations/html.spec.js, src/validations/html/slowparse.js
E.g. the string "<p>T" in the HTML input causes Slowparse to throw an uncaught error.
=> Catch slowparse errors

locales/en.json, spec/assertions/validations.js, spec/examples/validations/css.spec.js, src/validations/Validator.js, src/validations/css/prettycss.js
This stylesheet:
```css
p {
padding: 1px 1px 1px 1px 1px;
}
```
Yields an “extra tokens after value” error from PrettyCSS. This is
what we’d expect, since there is an extra `1px` at the end of the value,
which is not a valid way to write `padding`.
However, this will generate the same error:
```css
p {
padding: 1px
margin: 4px;
}
```
Since CSS is insensitive to newlines, the `margin` on the second line
appears to be a continuation of the value for `padding` on the first
line.
We can heuristically identify situations where the “extra tokens after
value” error is the result of a missing semicolon:
* The token that fails to parse is the first non-whitespace string on
its line
* The previous line does not end in a semicolon
So, we now get good error messages for each of these situations:
=> Distinguish between missing semicolon and extra tokens

locales/en.json, spec/examples/validations/html.spec.js, src/validations/html/slowparse.js
If you put space right after the opening angle bracket of an HTML tag, e.g. `< p>`, that’s not valid HTML.
From the parser’s standpoint, this looks like a tag whose name is `""`, the empty string. However, we can heuristically detect that this is actually a tag with an erroneous space character before the tag name, and give a more informative error message.
=> Better error message for space after the opening angle bracket of a tag

src/components/Dashboard.jsx
For long submenus (e.g. a long project list), Pop covers the list. Going behind the list wouldn’t look great either. So, just don’t show Pop when there is an active submenu.
=> Don’t show Pop when submenu is active

spec/examples/validations/html.spec.js, src/validations/html/slowparse.js
Slowparse will report a “mismatched close tag” when a stray closing tag sits at the very bottom of the entire document, e.g.:
```html
<!DOCTYPE html>
<html>
<head><title>Page Title</title></head>
<body></body>
</html>
</div>
```
The opening tag is reported as `#document-fragment`, so we can simply detect this and report it as an `unexpected-close-tag` instead.
=> Special case for “mismatched close tag” when open tag is the whole doc

locales/en.json, spec/examples/validations/css.spec.js, src/validations/css/prettycss.js
This is a missing opening curly brace:
```css
p
display: block;
}
```
This is a typo in the selector:
```css
p; div {
display: block;
}
```
Both look the same to our parsers, though. We can distinguish between the two by checking what type of token tripped the `block-expected` error in PrettyCSS—if it’s an identifier or whitespace, we can guess that it’s a missing curly; otherwise, we can surmise that it’s an invalid character in the selector.
=> Distinguish between missing opening curly and bogus character in selector

spec/examples/validations/html.spec.js, src/validations/html/htmllint.js
Turns out this, rather absurdly, throws an error when e.g. an `<img>` tag doesn’t self-close or have an explicit closing tag.
This means we get slightly less good behavior on actually unclosed tags, but it’s still basically fine.
=> Disable the tag-close check in htmllint

locales/en.json, spec/examples/validations/css.spec.js, src/validations/css/prettycss.js
E.g.:
```css
div {
padding: -2px;
z-index: 2.1;
}
```
Is invalid, because `padding` has to be nonnegative, and z-index has to be an integer. PrettyCSS already warns about this, so we just add mappings and translations.
=> Prevent invalid fractional and negative values

README.md, bower.json, src/components/Preview.jsx, src/config/previewFrameLibraries.js, src/util/generatePreview.js
* Added new module that mimics the structure of the existing libraries file for things that should be injected to the preview by Popcode developers, not the user.
* I had to bower install to get the project to start when checking out a fresh copy, so I added that step
* Didn't do anything test-wise since it doesn't look like there are any existing javascript validation tests
The sweetalert functionality is...fairly meh. Since it doesn't block, if there are multiple alerts, then it just renders the last one as a preview. And we can't replace prompt with it. We could do a lot more by patching it down the line, but it would take some dev effort to have the user writing synchronous, blocking code and us transforming it to be asynchronous with this stuff.
=> Replace alert() in preview with non-blocking sweetalert

npm-shrinkwrap.json, package.json
Flexbox support has been merged and released, so no need to use our
fork.
=> Back to official PrettyCSS release

src/components/Preview.jsx
The pop-out preview should be as unadorned as possible—no need to set up a base tag, an error handling script, etc.
=> Minimal modification to pop-out preview

spec/examples/actions/projects.spec.js, src/actions/index.js, src/actions/projects.js, src/reducers/projects.js
Fixes bug where switching projects causes all other projects in the list to disappear. This is because I had reversed one of the conditions in the filter for which projects to retain after a project switch.
=> Fix disappearing projects in list after switching projects

src/components/Preview.jsx, src/util/generatePreview.js
Not sure if you wanted to do anything fancier than this, it just ignores whatever is passed in, doesn't block, and returns the second parameter, or the empty string. This way users can continue to write code after prompts and do string methods, coerce types, etc, without getting errors (I'm sure there are cases where this is not true).
=> Disallow blocking prompt in preview

locales/en.json, src/components/Dashboard.jsx
When a student is signed in, Popcode will export their gist to GitHub under their account. This is better. Prompt before exporting a gist anonymously.
=> Confirm before exporting anonymous gist

config/browsers.json, gulpfile.babel.js, npm-shrinkwrap.json, package.json, src/application.js, src/components/Application.jsx, src/init.js
* Add a polyfill for ES6 Set, specifically to ensure that `Set.prototype.forEach` is available. Lodash relies on this, but some older browser versions that we can otherwise support don’t have it.
* Increase version requirements to IE11 and Firefox 28, which are respectively the first versions to fully support modern flexbox. Popcode’s layout heavily depends on flexbox.
* Pass list of supported browsers to `cssnext`/`autoprefixer`, so that our CSS will contain all appropriate vendor prefixes for the browser versions we support.
=> Improved support for old browsers

src/actions/index.js
When importing from a gist, we should gracefully handle one or more languages not having code present. This happens naturally when retrieving CSS and JavaScript, because for those languages we take *all* matching sections of the gist and join them together; thus the base case is joining an empty array, generating an empty string. In the case of HTML, however, it doesn’t make sense to concatenate multiple HTML sections, because each presumably contains a full HTML document; so, we just take the first. If no HTML document is present, this search yields an undefined value. So, explicitly fall back to an empty string.
=> Default to empty string when HTML not present in imported gist

src/services/Gists.js
The Gist API will reject a file that contains only whitespace. So, we need to trim the source before checking to see if it’s empty.
=> Don’t export whitespace-only source code to GitHub

spec/examples/actions/ui.spec.js, src/actions/index.js, src/actions/ui.js, src/components/Editor.jsx, src/components/Workspace.jsx, src/reducers/ui.js
In this situation:
* Type invalid code into an editor
* Minimize that editor
* Then click on the error message in the list
Expected behavior: The editor is maximized and focused, with the cursor at the position of the erroneous code.
Previous behavior: uncaught exception.
This pull request afforded an opportunity to finally fix one of my least favorite things about Popcode’s implementation, namely that the `Workspace` component held references to the `Editor` component instances that it owned. Worse, when an error was clicked, the `Workspace` would call a method *directly on the `Editor`*. This is not how components are supposed to work. It’s also the cause of the uncaught exception—with the editor minimized, the `Editor` component was not mounted, so the `Workspace` was trying to call a …
=> Handle click of error associated with minimized editor

src/util/generatePreview.js
Object.defineProperties by default uses configurable: true when
defining a property, which means that if you attempt to define that
property again later there will be a TypeError. This makes us fault
tolerant, which we want to be since the TypeError shows up in the UI.
=> Fix javascript error when redefining property

locales/en.json, npm-shrinkwrap.json, package.json, spec/examples/actions/projects.spec.js, spec/examples/actions/ui.spec.js, spec/helper.js, src/actions/index.js, src/actions/ui.js, src/components/ApplicationErrors.jsx, src/components/GlobalErrors.jsx, src/components/Workspace.jsx, src/css/application.css, src/reducers/ui.js, src/util/projectUtils.js
We saw two classes of sign in error: one where the user intentionally cancels sign in (by closing the popup without choosing to authorize), and another vaguer failure.
In the first case, we’ll display a specific message instructing the user to try again and click the green button:
In the second case, we’ll display a more general message, and also notify Bugsnag of the error, including the error code that came back from Firebase.
This means generally setting up a framework for displaying application-level errors in red banners at the top of the screen, which can then be dismissed.
=> Gracefully handle failed sign-in

npm-shrinkwrap.json, package.json, src/config/libraries.js, src/validations/css/css.js, src/validations/css/prettycss.js, src/validations/html/htmllint.js, src/validations/html/slowparse.js, src/validations/index.js, src/validations/javascript/esprima.js, src/validations/javascript/jshint.js, src/validations/linters.js, webpack.config.js
This reduces the size of the entry bundle by about 50%, from ~1.6MB to about 750K gzipped. Still have some work to do for sure, but it’s a real improvement.
Three changes:
* Linters are loaded asynchronously. The linters make up a big chunk of our total vendor code, and they’re generally not needed exactly at load time. So, we load the linters asynchronously, though still greedily, which is to say we initiate the async request as soon as the main bundle loads. This means the linters should still be available by the time the user actually needs to validate something, but downloading them is not blocking load of the initial UI.
* Remove libraries that no one is using. We keep jQuery, Lodash, Mustache, and Bootstrap, and ditch everything else. At some point we can bring them back, but I …
=> Reduce entry bundle size

src/util/generatePreview.js, src/validations/javascript/jshint.js
We’ve recently removed some libraries from the application, at least temporarily. Most likely no one is using them, but if a saved project does include a removed library, we want to gracefully handle that case.
Since we may reintroduce these libraries later, I don’t want to filter them out of the projects themselves; instead, I just want to safely handle cases where a library key does not refer to an available library.
=> Gracefully handle library keys referring to nonexistent libraries

templates/new.html
From observing students using the editor, this is just confusing.  Instead, just put a line of whitespace inside the body where the student can start typing.
=> Remove “put your code here” comment

gulpfile.babel.js
Needed to enable sourcemaps both at the Webpack level and the Uglify level.
=> Fix production sourcemaps

spec/examples/validations/css.spec.js, src/validations/css/prettycss.js
In the case that the entry in the CSS editor is nothing like actual CSS, PrettyCSS might return an error with no `token`. Since we use the `token` to determine the location of the error, in this case we just fall back to the first line.
=> Handle PrettyCSS error with no token

.travis.yml, README.md, karma.conf.js, npm-shrinkwrap.json, package.json, spec/examples/validations/css.spec.js
BrowserStack allows us to run tests on a bunch of real browsers. Cool!
One problem is that we need credentials to run tests on BrowserStack.  And since this is an open source project, that either means making my credentials public, or only allowing them to be used when run from the canonical `popcodeorg` repo. For now, we’ll go with the latter.
This means that PR tests will only be run in Firefox, which is available locally on Travis. This is not the end of the world, as we will still run the tests on the full suite of browsers before cutting a new release.
=> Run release build tests using BrowserStack

locales/en.json, src/components/Dashboard.jsx, src/components/Workspace.jsx, src/services/Gists.js
GitHub does not allow gists with no content. In this case, bail before attempting to send the gist to GitHub, and display an error message.
=> Fail fast if attempting to create a gist with no content

npm-shrinkwrap.json, package.json, webpack.config.js
Prior to 2.4.0, certain errors are not handled correctly, resulting in the reported error being an error in the error handler. This makes it impossible to know what the original error was.
This was [fixed in 2.4.0](https://github.com/michael/github/pull/354), meaning we will now get meaningful error reports for errors when interacting with the Gist API.
Apparently the 2.4.0 build failed, so there is no 2.4.0 on npm. For that reason we include the dependency off of GitHub, which means `dist` isn't built, which means we need to compile in the source files. So, a bit of extra configuration in WebPack to compile ES6 and also to point at the right module lookup paths.
=> Upgrade github-api to 2.4.0

src/components/Dashboard.jsx
Safari does not support this, but unfortunately the linter didn’t catch it because it is part of the browser API.
=> Import missing TextEncoder polyfill

locales/en.json, npm-shrinkwrap.json, package.json, src/components/Dashboard.jsx, src/components/Workspace.jsx, src/services/Gists.js
Various classes have observed situations in which newly-created gists, when opened in the new tab, yield a GitHub 404 page. This is odd behavior, considering we are just using the `html_url` returned by the GitHub API.
Bit of a shot in the dark here, since the error isn’t readily reproduced, but my theory right now is that we’re hitting an eventual consistency situation or a slightly laggy database replica on GitHub’s end.
To try to combat this, after creating (and possibly updating) the gist, we send an API request to fetch the newly created gist. If the request fails, we’ll retry with exponential backoff several times.
The hope is that a 404 on the web URL will correlate with a 404 in the API. There is certainly no guarantee of this, but it’s worth a shot.
=> Ensure we can read gist from GitHub API before attempting to open it

locales/en.json, src/actions/index.js
It’s entirely possible for a gist ID in the query param to refer to a nonexistent gist. In this case, we should display an error message and go about our day.
=> Gracefully handle 404 when trying to import a gist

src/css/application.css
Simple fix to the problem where in smaller window sizes, the Pop svg blocks the click target for the dashboard menu items. By bringing the dashboard menu items to the front, the Pop svg will not block them.
=> simple fix to bring dashboard items to the front

spec/examples/actions/index.spec.js, src/actions/index.js, src/services/Gists.js
popcode.json could later be extended to save any other metadata that
we want to.
Fixes: #195
=> Export libraries to popcode.json and reload when importing

spec/examples/validations/html.spec.js, src/validations/linters.js
In HTML5, a few close tags can be omitted, e.g. `<p>`. So, this is valid HTML:
```html
<!doctype html>
<html>
<body>
<p>My paragraph
</body>
</html>
```
However this confusing, inconsistent, and bad practice. Not something we want to teach students they can do.
So, we override the Slowparse parser to clear the list of tags that may be omitted. Directly reaching into the parser’s prototype and modifying one of its properties isn’t the most elegant-feeling solution, but it’s the only way I could find to do it given the API that Slowparse currently exposes.
=> Don’t allow omission of any close tags

spec/examples/validations/html.spec.js, src/validations/html/htmllint.js
By using `htmllint` `attr-name-style` `lowercase`, we were overzealously requiring attribute names consisted entirely of lowercase characters. In fact we want to allow dashes as well. Switch to the `dash` style, which matches the pattern we are in fact interested in.
=> Allow dashes in attribute names

package.json, src/components/Dashboard.jsx, src/css/application.css, static/index.html
Previously we had an issue with Pop encroaching into the button area of the dashboard with very small viewport heights. This fixes that issue.
In Chrome, the behavior is ideal: Pop will resize to accommodate both the width and height available to it.
In Firefox and Safari, Pop does not resize to accommodate small vertical space, but its container is `overflow:hidden` so at least it will not encroach.
This is accomplished by removing the absolute positioning of Pop within an expanding flex container. Instead, we add a expanding flex spacer above Pop, and then set Pop to take up only the space it needs. We further set a `max-width` and `max-height` on the SVG itself.
Fixes #189
=> Ensure Pop stays within bounds

src/components/Workspace.jsx
Otherwise we’re not getting useful backtrace information.
Also, Bugsnag throws a warning if you call `notifyException` with a string.
=> Ensure we are passing Error object to Bugsnag when auth fails

src/components/Dashboard.jsx
Exported gists are always opened in a new tab, rather than reusing the same tab. This is for two reasons:
1. It’s generally confusing to load the exported gist in an already-open tab, particularly as there is no way to focus it.
2. There is a crazy bug where if you export a gist, then open Popcode in the exported gist window, then try to export a gist again, it will reuse the window that Popcode is currently running in! Meaning it stops running, no gist is exported, and the spinner is forever.
So: Open a new window to `_blank`.
=> Always open gists in new tab

src/components/Dashboard.jsx
I’m now seeing an issue in production that @alexpelan had previously reported in a different branch, namely that the Gist export window closes as soon as it opens!
I set a bunch of breakpoints in production but could not make heads or tails of it. There does not appear to be an error occurring.
The one thing that that branch has in common with newly-released production code is calling `open` directly on a `data` URI, instead of calling it on `about:blank` and then setting the `location`. So, rolling back to that in hopes that it will help.
I cannot reproduce the error in dev at all.
=> Set window href after initial call to open()

src/components/Dashboard.jsx, src/components/Preview.jsx, src/util/index.js
It appears that a recent version of Chrome has introduced a regression that causes newly-opened windows to immediately close if they are opened with a data URI. This behavior definitely used to work fine, and it also works as expected in Firefox. [Here is a reduction of the bug](https://outoftime.github.io/presentations/openbug/index.html).
Even more oddly, I do not see this behavior in development, only production. Others have seen it in development, though.
Happily, opening `about:blank` and then immediately setting the `location.href` of the new window to the desired location (data URI) seems to work fine.
Fixes #505
=> Use location.href workaround to work around Chrome closing bug in popout

src/components/Preview.jsx, src/util/generatePreview.js
I just hardcoded to html doctype, since that's what our html validators force anyway. I couldn't find any way to programmatically get the doctype from the DOMParser output, and my other thought was to grab the current document's doctype (in case times change), but that involved some nasty parsing  (http://stackoverflow.com/a/10162353/265714 )
Fixes: #510
=> Force html doctype in generated preview

src/components/PreviewFrame.jsx
In order to keep from constantly adding and removing an `iframe` from the DOM, we keep the iframe around all the time, and just hide it when we don’t need it (e.g. when validations are in progress or there are errors).
In this case the `PreviewFrame` component is passed a blank `src`, because we don’t want to give potentially invalid HTML/CSS/JS to the frame, which could then cause runtime errors/console errors/etc.
However, in Safari, this constant switching from blank to non-blank `srcDoc` for the iframe causes it to intermittently (but pretty regularly) get “stuck” on a blank document, even when the `srcDoc` contains a document with content.
There is no particular reason that this should be the case, so it seems like a browser bug. We haven’t seen this behavior in Firefox or Chrome …
=> Explicitly use a blank `src` for preview frame when no source document is available

locales/en.json, src/components/Dashboard.jsx, src/components/Workspace.jsx
If the gist export takes a long time, the student may close the window before it completes (or fails). We want to handle this gracefully:
* If the export completes and the student has closed the window, we display an application error instructing the student to try again.
* If the export fails and the student has closed the window, we don’t try to close the window again.
Also used this as an opportunity to move the meat of the gist export logic out of the `Dashboard` and into the `Workspace`, since the latter as the view controller should take care of (or delegate to the action creators) pretty much anything interesting.
Threw in another small fix which is to always open a new tab for the exported gist, rather than reusing the same tab for successive exports (which is 100% confusing). …
=> Graceful handling of closed gist windows

src/services/Gists.js
If request to load gist fails, retry a few times with exponential backoff.
Fixes #278
Fixes #331
=> Retry loading gist if request fails

src/actions/index.js
Popcode is totally freezing when a certain student signs in. Since Firebase now creates opaque user IDs, I need to have an instructor grab her UID from the console so I can look at the data in her account and figure out what might be going on.
Relates to #527
=> Temporarily log the user ID on login

spec/examples/validations/html.spec.js, src/validations/html/htmlInspector.js
Certain malformed HTML may caused the parsed document to have a null `documentElement`. In this case, the `HTMLInspector` validator just bails, rather than passing `null` into `HTMLInspector`, which caused an uncaught error.
Fixes #324
=> Don’t attempt to inspect DOM if document root is null

npm-shrinkwrap.json, package.json
An erroneous escape sequence in the PrettyCSS tokenizer caused Popcode to freeze when a long, invalid URL value was added to the CSS, e.g.:
```css
div {
background: url("data:image/jpg;someverylongstringhere
}
```
(Note that there is no closing quotation mark or parenthesis)
The maintainer of PrettyCSS has pushed [a commit that fixes the problem](https://github.com/fidian/PrettyCSS/commit/dfab549b426df8f27f540e0637b810648b0b7dc1). Target a tag that points to this version directly until there is an official PrettyCSS release with the fix.
Fixes #527
=> Target PrettyCSS version with fix for catastrophic backtracking

src/components/Editor.jsx
ACE exposes a scrollToLine method so this ended up being trivial.
Fixes: #501
=> Scroll to line when error is clicked

locales/en.json, src/actions/index.js, src/components/NotificationList.jsx, src/components/notifications/GistImportError.jsx, src/components/notifications/index.js
If a gist import fails—for instance, because the classroom’s IP is rate
limited—we should at least show a good error message and a link to open
the gist, so students can copy the code in. This does that.
Fixes #538
=> Show error message with link when gist import fails

locales/en.json, src/components/EditorContainer.jsx, src/components/Output.jsx, src/components/Workspace.jsx, src/css/application.css
Addresses issue #514
Matched functionality that hides the HTML, CSS, JS panes to the Preview pane.
Slightly modified editor code so that Preview pane will match page width when HTML, CSS and JS panes are hidden.
=> #514 Make it possible to minimize the preview pane

.eslintrc, src/components/BrowserError.jsx, src/components/Dashboard.jsx, src/components/Editor.jsx, src/components/EditorContainer.jsx, src/components/ErrorItem.jsx, src/components/ErrorList.jsx, src/components/ErrorSublist.jsx, src/components/LibraryPicker.jsx, src/components/LibraryPickerItem.jsx, src/components/NotificationContainer.jsx, src/components/NotificationList.jsx, src/components/Output.jsx, src/components/Preview.jsx, src/components/PreviewFrame.jsx, src/components/ProjectList.jsx, src/components/Sidebar.jsx, src/components/Workspace.jsx, src/css/application.css
We’ve been using a variant of [Block, Element, Modifier](https://en.bem.info/) that conforms to (most of) the rules but does not follow the standard naming convention.
To make it easier to contribute to the project, switch to standard BEM naming convention so that the BEM documentation is maximally useful.
Specifically:
* Use double-underscore to delimit elements
* Use single-underscore to delimit modifiers
* Use kebab case (dashes) for internal word delimiting in block/element/modifier names
* Don’t nest elements (this is the rule we were breaking)
So, for example, `notificationList-notification--error` becomes `notification-list__notification_error`
And, `errorList-errorSublist-header` becomes `error-list__header` (no nested elements)
Fixes #555
=> CSS class names conform to standard BEM

README.md, npm-shrinkwrap.json, package.json
Adds a table of contents to the README, generated by [`doctoc`](https://github.com/thlorenz/doctoc). Also adds `doctoc` to development dependencies, and an NPM script to run it with the appropriate arguments.
=> Add TOC to README

webpack.config.js
Make Webpack configuration less sensitive to the specific layout of `node_modules`. Extracted from https://github.com/popcodeorg/popcode/pull/561, which may need to be put on hold until yarn properly handles optional dependencies.
Most usefully, changes the logic for loading stylelint rule modules—only load rules that are whitelisted, instead of loading all rules unless they’re blacklisted. Rules themselves often have external library dependencies, so this trims down the gzipped bundle size of the linter bundle from 415K to 355K.
=> More resilient Webpack configuration

webpack.config.js
On Windows, we’ll get paths with the `\` segment separator. So, our regexps can’t assume the separator will be `/`. Use `path.join` to construct the partial paths that go into the RegExp; this will also change any `/` passed in the `modulePath` argument to `\`, via the `path.normalize` method.
=> Construct path-matching patterns to be platform-independent

src/components/Workspace.jsx
At certain points—particularly when the workspace is first loading—there may not be a current project. The unload handler should not assume that there will be.
Fixes #574
=> Workspace unload handler should not assume current project

spec/assertions/validations.js, spec/examples/validations/javascript.spec.js, src/validations/javascript/esprima.js
Found a case in which the Esprima validator was unable to identify a token at the location of a parse error. Upon further investigation, it turned out that in this case the `row` and `column` reported in the error identified a location in the source that did not actually exist. However, it’s possible to have the tokenizer output tokens with the index of the token start and end in the overall source, rather than line/column information; the corresponding `index` reported in the error object appears to be more reliable.
As a bonus, the logic for locating the token is a bit simpler.
So, switch to using index rather than line/column to match up the error location to a token.
Fixes #576
=> More reliable location of error tokens

src/reducers/ui.js
The proximate motivation for this is that if the load project submenu is open when you sign out, the component will no longer be able to render at the moment the workspace is reset. This is because the projects list expects a current project, but at the moment there is not one.
So, the reducer for UI state consumes a `RESET_WORKSPACE` action and closes any active submenu.
This does brush up against a general ambivalence in the Redux world about whether complexity should live in action creators or reducers. For instance, in this case, another option would be for the action dispatcher that dispatches `RESET_WORKSPACE` to also dispatch a `DASHBOARD_SUBMENU_TOGGLED` action.
In general, my instinct is to encode that complexity in the action dispatchers, because it’s easier to follow the logic …
=> Close active submenu on workspace reset

src/validations/css/css.js, src/validations/css/prettycss.js, src/validations/css/stylelint.js, src/validations/html/htmlInspector.js, src/validations/html/htmllint.js, src/validations/importLinters.js, src/validations/index.js, src/validations/javascript/esprima.js, src/validations/javascript/jshint.js
One of the most common uncaught errors reported for Popcode is that it fails to load the asynchronous module that contains the linter libraries used for validations. To guard against this, we introduce an `importLinters()` function, which has the following safeguards:
* Wrap the `System.import` call in a `promiseRetry`, so we retry loading several times with exponential backoff
* If even after retrying the operation has still totally failed, reject the promise, but also null it out so that, next time we need the linters, we’ll start the process all over again.
Fixes #541
=> Retry asynchronous module load if first time fails

package.json, src/validations/css/css.js, src/validations/css/prettycss.js, src/validations/css/stylelint.js, src/validations/html/htmlInspector.js, src/validations/html/htmllint.js, src/validations/importLinters.js, src/validations/index.js, src/validations/javascript/esprima.js, src/validations/javascript/jshint.js, yarn.lock
Re-run of #587, which was reverted because of tons of uncaught errors getting thrown in production. Original PR description follows.
---
One of the most common uncaught errors reported for Popcode is that it fails to load the asynchronous module that contains the linter libraries used for validations. To guard against this, we introduce an `importLinters()` function, which has the following safeguards:
* Wrap the `System.import` call in a `promiseRetry`, so we retry loading several times with exponential backoff
* If even after retrying the operation has still totally failed, reject the promise, but also null it out so that, next time we need the linters, we’ll start the process all over again.
Fixes #541
=> Retry asynchronous module load if first time fails, take 2

spec/examples/actions/projects.spec.js, spec/examples/actions/user.spec.js, spec/helpers/createAndMutateProject.js, spec/helpers/dispatchAndWait.js, src/actions/index.js, src/actions/user.js
Adds test coverage for `logIn` and `logOut` actions, and moves them and their private function dependencies into the `actions/user` submodule.
This is done in anticipation of upgrading Firebase; the new SDK has a substantially new API, and we’ll need to change some action creator code to accommodate that, so first I wanted to make sure that code has good test coverage.
=> Tests for logIn/logOut actions

spec/examples/actions/user.spec.js, spec/helpers/MockFirebase.js, src/actions/bootstrap.js, src/actions/user.js, src/components/Dashboard.jsx, src/reducers/user.js, src/services/Gists.js
Until now, we’ve been directly storing the profile information in the `github` key of the Firebase response in the `info` key of our own user representation in the store. This means that knowledge of the particular structure of the Firebase user representation leaks throughout the application.
Now, instead, the user reducer maps the Firebase structure on to a normalized, flat user representation for internal use. Most relevant information is now a key in the top-level user object; the only exception is `accessTokens`, which is a map of provider to access token, in the unlikely(?) event we’ll be supporting authentication with other providers in the future.
This is in preparation for the Firebase SDK upgrade, which will in fact give us a different structure of the Firebase user …
=> Flatten user data structure in store

.eslintignore, package.json
Realized that `yarn run lint` does not lint specs. Was relying on syntastic to do this for me. This is important!
=> Lint code in spec directory

src/components/Output.jsx, src/components/Workspace.jsx, src/css/application.css
Addresses Issue #629.
Instead of going straight for `style: display-none`, decided to hide the panel using css class `output_hidden`. The `"_hidden"` string is appended to the class when the Output button is clicked.
=> #629 Hide output panel instead of removing it when Output button is clicked

package.json, spec/examples/actions/bootstrap.spec.js, spec/examples/actions/clients.spec.js, spec/examples/actions/ui.spec.js, spec/examples/actions/user.spec.js, src/actions/index.js, src/components/Workspace.jsx, src/createApplicationStore.js, src/reducers/index.js, src/util/Bugsnag.js, src/util/projectUtils.js, yarn.lock
To date we have used the built-in `combineReducers` from Redux to put together the output of different reducers into the single top-level store state. However, this creates an awkward shape for the state, namely that the top-level state is a plain JavaScript object, and all of its properties are Immutable objects.
Instead, use `redux-immutable`, which provides an implementation of `combineReducers` that merges subtrees into an Immutable Map, rather than a plain object. This creates a much more consistent situation where the entire state tree is Immutable.
This has been bothering me for a while.
=> Use Immutable root state for Redux store

TEST_PLAN.md, spec/examples/actions/bootstrap.spec.js, spec/examples/actions/user.spec.js, src/actions/bootstrap.js, src/actions/user.js
As the first step in introducing an invariant that changing login state does not affect the current project, remove the logic that under some circumstances changes the current project when logging in. In particular, if no changes had been made to the blank current project before logging in, Popcode would automatically load the last project the user had worked on as the current project.
Now, if you open Popcode and are already logged in, you will always see a blank project. If you log in explicitly, you will always see the project that was on the screen before logging in, even if it is an
untouched blank project.
This simplifies the behavior and code, and makes for an easier mental model of Popcode’s behavior.
See #635 for further discussion and motivation
=> Always keep current project on login

spec/examples/actions/user.spec.js, src/actions/user.js, src/reducers/currentProject.js, src/reducers/errors.js, src/reducers/projects.js
The following scenario is fairly common:
* Student logs in to Popcode
* Student does some work
* Student then realizes they are logged in to the wrong account (because the browser was logged in to a different GitHub)
* Student “loses” their work because logging out resets the workspace
While the work the student did was, in fact, still available in the account they were logged in to, they may not have access to it, and this is generally an inconvenient situation.
We thus change the logic to only reset the workspace on logout if the current project was not locally modified.
This is particularly important because the forthcoming Firebase upgrade will mean that Popcode sessions are shared between all browser tabs. So, logging out of one tab will log you out of all tabs. This would add a …
=> Keep project when logging out if locally modified

TEST_PLAN.md, config/firebase-auth.json, package.json, spec/examples/actions/bootstrap.spec.js, spec/examples/actions/user.spec.js, spec/helpers/MockFirebase.js, spec/helpers/dispatchAndWait.js, spec/helpers/promiseTicks.js, spec/helpers/waitForAsync.js, src/actions/bootstrap.js, src/actions/user.js, src/clients/firebaseAuth.js, src/components/Dashboard.jsx, src/components/Workspace.jsx, src/config.js, src/persistors/FirebasePersistor.js, src/reducers/user.js, src/services/Gists.js, src/services/appFirebase.js, src/services/rxjs.js, yarn.lock
Version 2 of the Firebase SDK has been deprecated for some time in favor of Firebase 3. It’s important that we stay up to date, especially as a large number of the uncaught errors in production are inscrutable authentication errors coming from Firebase.
There are some fairly superficial differences between the versions in terms of the API and the shape of the data returned from it. There are also two very significant changes in Firebase 3:
* Credentials are no longer retained between browser sessions. So, even if the user is currently logged in to Firebase when Popcode bootstraps, it won’t give you the user’s GitHub auth credentials.
* All login sessions are long-lived and global. If you are logged in to Firebase in one tab, you are permanently logged in, and you’re logged in in all tabs. …
=> Upgrade to Firebase SDK 3

src/config.js
`process.env` is statically evaluated by Webpack, which replaces expressions with literal values in compiled code. Using lodash `get` prevents this static analysis from happening.
=> Don’t use lodash get to access process.env

spec/examples/actions/user.spec.js, spec/helpers/MockFirebase.js, src/reducers/user.js
Apparently the `displayName` and `photoURL` methods are not consistently available on the root Firebase user object. These properties are still, however, available on the `providerData`, which contains raw information from GitHub. So, prefer the first `providerData` record available as the source of profile data, falling back to the root object.
Fixes bug where avatar and name may not appear in the sidebar in production when users are logged in.
=> Use providerData for profile data if available

karma.conf.js, src/util/minimalStylelint.js, webpack.config.js, yarn.lock
Update all dependencies to the latest version allowed by the current constraints specified in `package.json`. Will follow up with major version upgrades where needed.
Only a couple of actual changes needed:
* For Karma, we no longer override the webpack `entry` to be `null`, because apparently that’s not allowed
* Stylelint’s files are now in its `lib` directory, not its `dist` directory
=> Update non-breaking dependencies

src/reducers/projects.js
During bootstrap, we may invoke a logout before the environment is completely set up (specifically, if there is an active Firebase session but the session heartbeat cookie has expired). In this case, a `RESET_WORKSPACE` action is triggered by the auth state handler, previously causing the `projects` reducer to incorrectly set its state to a map of `null` to `undefined`.
Now, the `RESET_WORKSPACE` handler checks to see if its input project key is nil, and if so, it just returns an empty map.
This isn’t an entirely satisfying solution—in particular, we really shouldn’t be firing the auth state change handler for a logout that is performed as part of bootstrap. That logic should only be run for auth state changes that occur after bootstrap. But I need to spend a bit more time thinking about …
=> Don’t attempt to retain current project on reset if there isn’t one

locales/en/translation.json, src/components/Workspace.jsx
Ideally, we’d like to retry sign in if a network error causes it to fail. However, our only interface to signing in is to call the `signInWithPopup()` method of Firebase, which results in a blocked popup if it’s not called in an execution context that was initiated by a user action.
So, just fail with a slightly more descriptive error, and don’t send the error on to Bugsnag.
Fixes #659
=> More descriptive error when auth fails because of network error

src/components/Workspace.jsx
If the student clicks “Sign In”, then clicks it again without closing the first pop-up or completing sign-in, Firebase will throw an error.
In this case, the best approach is to just let the student continue login via the new popup. The original one will still be orphaned in the background, but there’s nothing we can do about this (we don’t get a reference to the window that we can use to close it).
The main alternative would be to disable the Sign In button while sign-in is outstanding, but I think this would be a worse experience, since the student has probably lost track of the original pop-up and it would be unclear why the link was disabled.
Fixes #650 
Fixes #661 
Fixes #665
Fixes #668
=> Ignore auth/cancelled-popup-request error on sign in

package.json, yarn.lock
In particular, I’m hoping this will fix an issue with an uncaught "Network Error" getting thrown in some circumstances when there should just be a promise rejection (although the release notes do not give me great hope).
If nothing else, we’ll see the errors pop back up.
Fixes #660
Fixes #663
Fixes #675
=> Upgrade Firebase client

spec/examples/validations/css.spec.js, src/validations/css/prettycss.js
A particular bit of CSS exposes two errors in the heuristic detection of missing semicolons in CSS:
```css
button{border:20px solid b;
}
```
While none of our linters directly reports a missing semicolon, we use a heuristic to interpret PrettyCSS’s `extra-tokens-after-value` as a missing semicolon if the following is true:
1. The line with the error begins with the token reported as extraneous
2. The previous line does not end with a semicolon
However, the logic for each of these conditions was flawed:
1. The check for whether the line started with the bad token used a simple prefix substring match (so the extraneous `b` above matches the beginning of `button`)
2. We checked the previous line for a semicolon even if there was no previous line (i.e. the error occurred on the first line of …
=> Handle edge cases in heuristic detection of missing CSS semicolons

src/util/Bugsnag.js
Passing a rejection reason of arbitrary type as metadata doesn’t help much because the metadata is expected to be an object. Instead, stringify the reason as JSON and pass it as the error message.
Fixes #670
=> Try harder to pass reason for unhandled rejection to Bugsnag

locales/en/translation.json, src/components/Workspace.jsx
Firebase can’t perform login if the user has disabled third-party cookies. Catch this error and display a message asking them to change their browser settings.
Fixes #669 
Fixes #673
=> Handle third-party cookies disabled error

package.json, yarn.lock
Updates ACE from 1.2.3 to 1.2.6 (not sure why brace doesn’t use the same versions)
=> Upgrade brace

config/browsers.json, src/init/DOMParserShim.js, src/init/index.js, src/util/generatePreview.js
Chrome 30 does not support `DOMParser.parseFromString` for HTML, even though [MDN says it does](https://developer.mozilla.org/en-US/docs/Web/API/DOMParser#Browser_compatibility). So, adapt the polyfill from that selfsame article to provide a working parser in older browsers.
This allows us to support Chrome versions as old as 22 (the first version to have a working implementation of standard flexbox).
Fixes #722
=> Shim DOMParser.parseFromString to support HTML parsing on old browsers

locales/en/translation.json, package.json, src/components/ErrorItem.jsx, src/components/PreviewFrame.jsx, src/config/previewFrameLibraries.js, src/util/generatePreview.js, webpack.config.js, yarn.lock
JS Bin’s [`loop-protect`](https://github.com/jsbin/loop-protect) has worked pretty well, but unfortunately its regular expression-based heuristic detection of loops [fails to detect real-world cases of infinite loops](https://github.com/popcodeorg/popcode/issues/706). So, I wrote a replacement library called [`loop-breaker`](https://github.com/popcodeorg/loop-breaker), which uses `recast` to parse the code into an AST and adds breaking code into loops in that structure. This guarantees that all loops are checked.
Fixes #706
=> Swap in loop-breaker for loop-protect

locales/en/translation.json, package.json, src/components/ErrorItem.jsx, src/components/PreviewFrame.jsx, src/config/previewFrameLibraries.js, src/util/generatePreview.js, src/validations/javascript/esprima.js, webpack.config.js, yarn.lock
Restores the [switch to loop-breaker](https://github.com/popcodeorg/popcode/pull/726), which I had to revert because certain JavaScript inputs were causing the environment to throw an uncaught exception.
It turns out that the main problem was code that had a single slash at the beginning of the line (this was likely intended to be a double-slash for a comment). This causes esprima to throw an “invalid regular expression” error.
```js
// Tiny Turtle Setup. Avoid modifying these lines of code!
var adjCanvasSize = document.getElementsByTagName('canvas')[0];
adjCanvasSize.width  = 400;
adjCanvasSize.height = 400;
TinyTurtle.apply(window);
// Start writing code here
function rectangle(x, y){
forward(x);
right(90);
forward(y);
right(90);
forward(x);
right(90);
forward(y);
}
function house(x){ …
```
=> Loop-breaker take 2

src/components/Output.jsx, src/components/Workspace.jsx, src/css/application.css
If a very long token (e.g. a data URI) appears in an error message, [the column will expand to fit its contents, causing it to consume the entire width of the container, and causing the editors to disappear](https://github.com/popcodeorg/popcode/issues/548).
I couldn’t find a completely satisfactory solution using flex all the way down; the interaction between the contents size and the flex properties is not well-documented, but it is certainly sensitive to the size of the content.
By wrapping the contents of each column in an absolutely positioned div that fills its container horizontally and vertically, we can get exactly the behavior we want.  The use of absolute positioning here means that the contents of the columns cannot affect the layout of the columns; it breaks them out of the …
=> Absolutely position column contents

src/actions/index.js, src/actions/projects.js, src/reducers/errors.js, src/reducers/projects.js, src/sagas/errors.js, src/sagas/projects.js, test/unit/reducers/errors.js, test/unit/reducers/projects.js, test/unit/sagas/errors.js, test/unit/sagas/projects.js
Another conversion of a thunk action workflow to pure sagas and reducers. This is handling the `UPDATE_PROJECT_SOURCE` action, which is dispatched when the user modifies the source in an editor.
Architecture is as follows:
**Workspace dispatches `PROJECT_SOURCE_EDITED`**
**`projects` reducer consumes `PROJECT_SOURCE_EDITED`
* Updates source accordingly
**`errors` reducer consumes `PROJECT_SOURCE_EDITED`**
* Sets error state for source to `validating`
**`projects` saga consumes `PROJECT_SOURCE_EDITED`**
* Saves the project
**`errors` saga consumes `PROJECT_SOURCE_EDITED`**
* Cancels any in-progress validation for that source
* Initiates validation for the source
One notable thing here is the first use of `redux-saga`’s task cancellation feature. In particular, if a user is typing quickly, …
=> As-you-type validation handled by sagas and reducers

spec/examples/validations/javascript.spec.js, src/validations/javascript/jshint.js
This fixes issue #719.
This looks to have to been a design decision by JSLint to consider use of "hoisting" a bad practice. JSHint has added the option to override it if you want to.  
http://jshint.com/docs/options/#latedef
=> add jshint rule to allow function hoisting

locales/en/translation.json, src/components/Application.jsx, src/components/IEBrowserError.jsx
This fixes issue #517.  Let me know if you'd like other text, etc.
Again, I didn't add tests for this component-level change because the dependencies aren't there, but will add them when a library is chosen.
sorry to bombard you with pull requests : ) Just trying to get more real-world react experience and this is a neat app.
=> add specific error message for ie or edge indicating they aren't supported

src/css/application.css
user-select: none makes the text unselectable and pointer-events: none
makes it so the click event falls through to the editor, which handles
it.
Fixes: #363
=> Make editor zero-state unselectable, make click focus editor

locales/en/translation.json, spec/examples/validations/html.spec.js, src/validations/html/slowparse.js
Addresses https://github.com/popcodeorg/popcode/issues/347
I checked `htmllint` and `slowparse` and neither had a built in error for this case, hence the fallback to the custom error detector.
I tried to match the tone of the other error messages, but please let me know if I can make the messaging clearer.
=> Display a specific error for an empty <title> tag

src/components/Editor.jsx
Fixes https://github.com/popcodeorg/popcode/issues/313
It turns out that ACE comes with a bunch of keyboard shortcuts out of the box, including search. It wasn't working because the necessary extension script wasn't being loaded:
Making the script available -> instant search capability!
I'd imagine that there are some other great shortcuts that we're erroring out on (here's the basic list of commands: https://github.com/ajaxorg/ace/blob/master/lib/ace/commands/default_commands.js)
=> Make search-in-code work

spec/examples/actions/projects.spec.js, src/actions/index.js, src/actions/projects.js, src/reducers/errors.js, src/reducers/projects.js, src/sagas/errors.js, src/sagas/projects.js, test/unit/reducers/errors.js, test/unit/reducers/projects.js, test/unit/sagas/errors.js, test/unit/sagas/projects.js
**Workspace component issues `TOGGLE_LIBRARY`**
**`projects` reducer consumes `TOGGLE_LIBRARY`**
* Updates library state
* Updates `updatedAt`
**`projects` saga consumes `TOGGLE_LIBRARY`**
* Saves current project
**`errors` saga consumes `TOGGLE_LIBRARY`**
* Initiates validation for project
**`errors` reducer consumes `TOGGLE_LIBRARY`**
* Sets project validation state to validating
=> Migrate library toggle logic from thunk to sagas and reducers

src/css/application.css, static/images/pop/thinking.svg, static/index.html
Addresses the startup portion of https://github.com/popcodeorg/popcode/issues/781
Here's a recording of the standard page load from popcode.org
And here's a recording of a page load of popcode.org with a gist querystring (also shows that the pre-existing chill loader is unchanged)
=> Statically render "chill" loader while waiting for React

package.json
Forgot to add the `test` directory to the linter args when I originally set it up.
=> Lint unit tests

src/components/EditorsColumn.jsx, src/components/Workspace.jsx
As suggested in https://github.com/popcodeorg/popcode/issues/302#issuecomment-297600122.
This is mostly cut/copypasta from `Workspace.jsx`, with some minor tweaks (using destructuring and `connect` a bit more aggressively).
@outoftime I'm going to file a PR (probably this weekend) against this branch (or `master` if this gets merged first) with an updated version of the demo also mentioned in https://github.com/popcodeorg/popcode/issues/302#issuecomment-297600122.
=> Move <Workspace>._renderEditors into new <EditorsColumn> component

src/actions/index.js, src/actions/projects.js, src/components/EditorContainer.jsx, src/components/EditorsColumn.jsx, src/components/Output.jsx, src/components/Sidebar.jsx, src/components/Workspace.jsx, src/reducers/projects.js, src/reducers/ui.js, src/services/Gists.js, test/helpers/factory.js, test/unit/reducers/projects.js, test/unit/reducers/ui.js
This patch updates Popcode to persist information about which of the editors (incl. "Output") are currently minimized. The information is stored in an array under the key `minimizedComponents` in a project's `popcode.json` file. My implementation moves the `minimizedComponents` state from `ui` to `projects`, since the `popcode.json` file gets *created from* the `project` state. Is that cool? I could modify the implementation so that the `minimizedComponents` state stays under the `ui` subtree, but I think it would require some extra logic during the dehydrate/rehydrate `popcode.json` steps.
Also: on this branch, if you visit Popcode, minimize and maximize an editor, and then close the tab, you get a dialog box warning that you might lose unsaved changes. It's because in …
=> Sticky editor open/close state

package.json, src/actions/index.js, src/actions/ui.js, src/components/EditorContainer.jsx, src/components/EditorsColumn.jsx, src/components/Workspace.jsx, src/css/application.css, src/reducers/ui.js, src/util/resize.js, test/unit/reducers/ui.js, yarn.lock
Addresses part of https://github.com/popcodeorg/popcode/issues/302 (horizontal resizing should be comparatively easy to add later)
@outoftime I feel a bit silly turning `EditorsColumn` back into a stateful component here, but I believe it's necessary as long as the implementation relies on refs. Speaking of refs, I looked up a few declarative-style solutions for managing element height, and didn't find anything that solid (nothing with >100 stars && actively maintained). Still, the ref management here is the part I'm least satisfied with. Please let me know if you have any better ideas/libraries for this!
OTOH moving from `state` to `redux` went smoothly and the dragging might feel just a little jittery but I don't think it's too bad.
This also happens to fix …
=> Make editor windows vertically resizable

package.json, src/sagas/.eslintrc, yarn.lock
Upgrades all packages to latest semver-compatible versions. Also upgrade `sinon` to satisfy a peer dependency introduced by the semver upgrade.
Will go through the major upgrades in separate pull requests.
I did have to disable `import/order` linter rule in Saga-related code, because of some weird behavior with that linter in the latest version of `redux-saga`
=> Upgrade to latest semver-compatible packages; upgrade sinon

package.json, yarn.lock
This reverts commit 3f36633e0e2c57c42f75a2715b495119458162de.
Causes a build error that I somehow didn’t catch before.
Fixes #822
=> Revert "Upgrade babel-loader"

package.json, src/actions/index.js, src/createApplicationStore.js, yarn.lock
We no longer have any thunk actions that are used in live code paths.  Remove a few vestigial ones that had stuck around, and most of the other meaningful code in `actions/index`. The end goal is for `actions/index` to only re-export functions from modules within `actions`, and at this point we’re very close to that goal (just need to move a handful of trivial actions into child modules, and write tests for them).
Also removes `redux-thunk` from dependencies.
=> Remove redux-thunk and dead code in actions/index

spec/examples/actions/ui.spec.js, src/actions/index.js, src/actions/ui.js, src/components/Workspace.jsx, src/reducers/projects.js, src/reducers/ui.js, test/unit/reducers/projects.js, test/unit/reducers/ui.js
Previously the Workspace component’s handler for line focus would dispatch an `unhideComponent` action from the handler for a focused line request.  This had trivially buggy behavior in that it omitted the required first argument to `unhideComponent`, which should have been the current project ID.
However, it also doesn’t follow the recently adopted pattern of reducers knowing what to do in response to actions, rather than procedural code dispatching multiple actions to deal with different aspects of responding to a particular user action or external event.
So, remove the call to `unhideComponent` and instead have the `ui` reducer handle the focus line action.
Also while we’re in there, rename the rather awkward `userRequestedFocusedLine` to `focusLine`, following the convention of using …
=> Reducer unhides relevant editor when line focused

.stylelintrc.json, package.json, src/components/Dashboard.jsx, src/css/application.css, yarn.lock
Adds the `stylelint-selector-bem-pattern` linter and configures it. Uses the BEM preset with global exceptions for selecting `<svg>` and `<path>` elements since we can’t give them class names.
Use the `@define` comment method to mark off components within the single big stylesheet. I think it‘s about time to break each component into its own file, but getting the postcss `@import` of it all to work properly seems non-trivial, so I figured this would be a good first step.
Also:
* Move all the `layout` component selectors into one place
* Make `fontawesome` a utility element rather than its own component
=> Add stylelint enforcement of BEM pattern

gulpfile.js, package.json, webpack.config.js, yarn.lock
When running the dev server or autotest, there are several warnings. No longer:
* Passes a string query into `i18next-resource-store-loader`, because it uses a method that expects a string
* Use `yargs` instead of `gulp.env`, because `gulp.env` is deprecated
* Stubs out various modules in dependencies that attempt dynamic requires
=> Remove warnings output during JS build

.eslintrc, src/actions/index.js, src/actions/ui.js, src/components/EditorsColumn.jsx, src/components/Output.jsx, src/components/Workspace.jsx, src/css/application.css, src/reducers/ui.js, src/util/resize.js, test/unit/reducers/ui.js
The second half of https://github.com/popcodeorg/popcode/issues/302!
All of the changes in `resize.js` are one-to-one vocabulary changes:
- `height` -> `size`
- `y` -> `position`
- `editors.verticalFlex` -> `workspace.columnFlex`
I also modified the editor hide/unhide behavior to allow for e.g. horizontal resize proportions to remain constant when an editor component is hidden.
The only complication is in capturing the movement event when the mouse moves over the preview iframe. The most graceful hacky solution I could come up with was enabling same-origin rights in the iframe and manually dispatching a rough clone of the internally captured event, with adjustments for the iframe's position.
If same-origin is a deal breaker I can restructure in terms of `postMessage`.
Recording of …
=> Horizontally resizeable workspace columns

src/util/generatePreview.js
Also loaded css/js as an internal source instead of a data64 src text. Discovered that loading via data64 does not happen synchronously as expected.
Fixes #815
=> Insert popcode JS and CSS libraries on the top of the head tag

.eslintrc, src/actions/index.js, src/actions/ui.js, src/components/Output.jsx, src/components/Preview.jsx, src/components/Workspace.jsx, src/css/application.css, src/reducers/ui.js, src/util/generatePreview.js, test/unit/reducers/ui.js
This PR is the cleaned up version of this branch: https://github.com/popcodeorg/popcode/pull/862 and is a pairing collaboration between @kaylee42 and I.
The feature adds a refresh button to the preview pane that resets the state of the code to before the js has run. It looks like this:
Often while in the classroom, I saw students either confused as to how to play an animation over that was js based. They would either open the popout window or applying a roundabout way like adding extra spaces to their code and then deleting them to get popcode to re-render.
This feature is meant to add that functionality without having the students editing their code. It uses a timestamp of the last time the refresh button was clicked and inserts that into a comment in the preview pane html to force React …
=> Reset button

src/util/generatePreview.js
Reverts popcodeorg/popcode#859
Bootstrap does not work properly after the change in #859. Reverting this PR pending investigation.
=> Revert "Insert popcode JS and CSS libraries on the top of the head tag"

package.json, webpack.config.js, yarn.lock
* Use currently preferred configuration format—`module.rules` instead of `module.loaders`, `use` instead of `loader`, etc.
* Put general loader configurations first, then module-specific workarounds
* Use `node: {fs: 'empty'}` to stub out `fs` rather than doing it with a substitute loader
This is extracted from an attempt to port our build tooling to Blendid, which I have since decided not to do.
Upgrade `babel-loader` and `svg-react-loader` to avoid warnings.
=> Clean up webpack config

.projections.json, package.json, src/analyzers/index.js, src/components/Workspace.jsx, src/containers/ErrorReport.js, src/containers/Preview.js, src/sagas/clients.js, src/sagas/errors.js, src/selectors/getCurrentProject.js, src/selectors/getErrors.js, src/selectors/getLastRefreshTimestamp.js, src/selectors/index.js, src/selectors/isCurrentProjectSyntacticallyValid.js, src/selectors/isCurrentlyValidating.js, src/selectors/isUserTyping.js, src/util/Bugsnag.js, src/util/projectUtils.js, test/helpers/Scenario.js, test/unit/Analyzer.js, yarn.lock
Adds the `reselect` library, which enables the creation of memoized selectors. The job of selector is to derive information from the state tree in a form that’s useful to the UI.
A few motivations here:
* `reselect` selectors are memoized, meaning expensive calculations can be done once and retained until the inputs change. This is good for runtime efficiency.
* Selector memoization also means that we can get all the benefits of `Immutable` outside the Redux store without having to actually pass around `Immutable` objects. In particular, as long as `toJS()` calls are happening inside a selector, we have a guarantee of object-level equality of the selectors’ output as long as the data hasn’t changed.
* Finally, selectors give us a first-class place to put code that derives useful …
=> Add reselect and use it to extract data from store in containers

src/components/Dashboard.jsx, src/components/Workspace.jsx, src/components/index.js, src/containers/Dashboard.js, src/containers/index.js, src/selectors/getActiveSubmenu.js, src/selectors/getAllProjects.js, src/selectors/getCurrentUser.js, src/selectors/getCurrentValidationState.js, src/selectors/index.js, src/selectors/isCurrentlyValidating.js, src/selectors/isDashboardOpen.js, src/selectors/isGistExportInProgress.js
Adds a `Dashboard` container, which connects the Redux store to the `<Dashboard>` component. Mostly neutral with respect to the props `<Dashboard>` takes; the only exception is the `onLibraryToggled` callback, which is now passed the `projectKey` explicitly by `<Dashboard>` because `mapDispatchToProps` doesn’t have access to `state`.
=> Dashboard container

src/sagas/clients.js, src/sagas/errors.js, src/sagas/index.js, src/sagas/projects.js, src/sagas/ui.js, src/sagas/user.js
Yielding an array directly is deprecated. Instead use `all()` effect.
Fixes #900
=> Use redux-saga all() effect

package.json, src/clients/firebaseAuth.js, src/reducers/user.js, test/helpers/factory.js, test/unit/sagas/user.js, yarn.lock
Upgrades library version to 4.1.3. There are breaking changes that affect us:
https://firebase.google.com/support/release-notes/js#4.0.0
Specifically the change of `provider` to `providerId` in `credential`.
=> Upgrade Firebase

.gitignore
Even though it’s no longer used, anyone with an existing development environment will have stuff in there that git will consider untracked files. Keep things simple and just retain it in .gitignore.
=> Put static/compiled back in .gitignore

package.json, src/application.js, webpack.config.js, yarn.lock
Builds on #860, installing the Webpack `offline-plugin` to allow offline access to Popcode.
Pretty simple integration. One thing I don’t love is listing out all the fonts/images directly, but other than parsing the CSS I don’t have a great idea for how to keep that deduplicated.
Closes #860
Fixes #315
=> Offline access

package.json, yarn.lock
[Only change in the major upgrade](https://github.com/i18next/i18next/blob/master/CHANGELOG.md#800) doesn’t affect us.
=> Upgrade i18next to 8.4.3

src/components/Dashboard.jsx
During bootstrap, the `currentProject` may not yet be loaded. However, the `<ProjectList>` component requires `currentProject` to be set. So, don’t render the `<ProjectList>` if we don’t yet have a `currentProject`.
Fixes #920
Fixes #909
Fixes #843
Fixes #798
Fixes #758
=> Don’t render project list if the current project hasn’t resolved yet

package.json, yarn.lock
Only used for html-inspector, which still seems to work.
=> Upgrade imports-loader

src/config/libraries.js, src/util/generatePreview.js
Bootstrap’s JavaScript depends on jQuery. Currently it’s actually impossible to get Boostrap’s JS to work because the `generatePreview` code adds scripts in the reverse order of their specification in the configuration (this is an unintentional/emergent effect of the way the code is written).
We fix by doing two things:
* Add a `dependsOn` mechanism for libraries. When the `previewGenerator` decides which libraries to put on the page, it looks at the `dependsOn` and, if present, recurses through the dependencies. Note that there is no guard against circular dependencies, but since a circular dependency scenario could only be caused by a misconfiguration in our code, I’m not too worried about it.
* Modify the logic for where library scripts are put on the page.  Specifically, we identify …
=> Automatically load jQuery when Bootstrap is loaded

src/containers/Preview.js
Expects `language` and `error`, but the `Preview` prop `onRuntimeError` was only being passed the error itself. Reasonable, since runtime errors in fact only happen with JavaScript. So, the container fills in the language.
Fixes #910
Fixes #934
=> Pass correct arguments to addRuntimeError action creator

src/containers/Dashboard.js
Another Firebase login error, seems to happen in similar situations to `web-storage-unsupported` so we just use the same error.
Fixes #796
Fixes #818
Fixes #933
=> Catch operation-not-supported-in-this-environment

locales/en/translation.json, package.json, src/validations/html.js, src/validations/html/htmllint.js, src/validations/html/rules/Code.js, src/validations/html/rules/MismatchedTag.js, src/validations/html/rules/index.js, src/validations/html/runRules.js, src/validations/html/slowparse.js, test/unit/validations/html.js, test/unit/validations/html/rules.js, test/unit/validations/html/runRules.js, yarn.lock
An attempt to fix #562, although goes a bit farther by deprecating `mismatched-close-tag` in favor of three distinct errors:
- `misplaced-close-tag`: **(new)** suggests moving a spare unopened close tag
- `unclosed-tag-by-mismatched-close-tag`: **(new)** suggests adding a close tag right before the mismatched close tag
- `unexpected-close-tag`: preexisting
This pull request introduces a new HTML `Validator` that performs its own lexical analysis using the [SAX](https://en.wikipedia.org/wiki/Simple_API_for_XML) parser from [`parse5`](https://github.com/inikulin/parse5) to parse HTML tokens.
The code is a bit complex, so feel free to offer readability suggestions. Thanks!
=> Deprecate mismatched-close-tag into more precise errors

.travis.yml
Travis has a really old version of `yarn`, which is, I’m guessing, why `yarn check` is failing on CI but not locally. So, add explicit configuration for Travis to install the same version of `yarn` that is in `package.json` etc.
=> Explicitly install the right version of yarn

.eslintrc, src/reducers/ui.js
Eventually I will get around to refactoring the reducers to not use enormous case statements, but for now, bumping the complexity all the time is not a good use of anyone’s time or code review.
=> Just turn off complexity rule for ui reducer until further notice

src/components/Dashboard.jsx, src/components/Workspace.jsx, src/css/application.css
Previously the top-level layout was based on a flex row, containing the dashboard, sidebar, and main editing environment. This worked pretty well because usually we didn’t have anything else that needed horizontal space. The exception was notifications, which ended up just pushing the rest of the environment down a bit, such that the bottom was outside the viewport—definitely a bug, but not the end of the world.
This fixes that bug by creating a top-level column flex and then within it a row flex. The column flex currently just contains any notifications followed by the main user interface. However, the real motivation for this is to allow us to add an always-on  top bar for the layout overhaul, which will follow in a subsequent PR.
=> Flex column at top level of layout

.projections.json, locales/en/translation.json, src/actions/index.js, src/actions/ui.js, src/components/Dashboard.jsx, src/components/TopBar/CurrentUser.jsx, src/components/TopBar/CurrentUserMenu.jsx, src/components/TopBar/index.jsx, src/containers/Dashboard.js, src/containers/TopBar.js, src/css/application.css, src/reducers/ui.js, src/selectors/getOpenTopBarMenu.js, src/selectors/index.js, test/unit/reducers/ui.js
If coder is not logged in, display a prompt “Log in to save”
If coder is logged in, display avatar and display name, along with a down arrow indicating the user badge is clickable.
When the user badge is clicked, expose a “Log Out” prompt
Another step toward #779
=> Move current user unit to the top bar

config/firebase-auth.json, src/clients/firebase.js, src/reducers/user.js, test/helpers/factory.js, test/unit/reducers/user.js
If the user has not added a real name to their GitHub profile, we now fall back to using their GitHub username.
The Firebase `UserCredential` object can optionally contain an `additionalUserInfo` key that contains the raw profile data from the provider. This is useful e.g. in the case of GitHub (the only case!) for retrieving the user’s username (which, frustratingly, is not available via the normalized Firebase user profile).
However, when re-authenticating (e.g. loading Popcode while already logged in), that data is not made available to the auth event handler, and as far as I can tell there is no way to ask for it. So, whenever the user logs in explicitly, we grab the `additionalUserInfo` and store it in the Firebase database; then we retrieve it on re-authentication and add it to the …
=> Use username as display name if there is no display name

src/util/generatePreview.js
We were missing the TextEncoder polyfill in the `generatePreview` module; this is fine on modern browsers but breaks on older supported versions of Chrome and Safari (it also breaks IE and Edge early enough that the unsupported browser message doesn’t show up).
Fixes #964
Fixes #960
Fixes #953
Fixes #947
Fixes #940
Fixes #912
Fixes #908
Fixes #906
Fixes #888
Fixes #872
Fixes #865
=> Use TextEncoder polyfill in a place where we were missing it

package.json, webpack.config.js, yarn.lock
Upgrades:
* All semver-compatible dependencies
* stylelint
* postcss-cssnext
A few left outated because latest versions break the project in inscrutable ways.
=> Upgrade dependencies

.projections.json, src/components/Dashboard.jsx, src/components/Sidebar.jsx, src/components/TopBar/CurrentUser.jsx, src/components/TopBar/TextSize.jsx, src/components/TopBar/index.jsx, src/components/Workspace.jsx, src/components/notifications/SnapshotNotification.jsx, src/containers/TopBar.js, src/css/application.css, src/selectors/index.js, src/selectors/isTextSizeLarge.js
Next step in the move everything to the top bar project—moves the text size toggle.
Also consolidates the `u__fontawesome` element into the better `u__icon`, and removes a pesky projection.
Another step in #779
=> Move text size toggle to the top bar

src/components/Dashboard.jsx, src/components/TopBar/SnapshotButton.jsx, src/components/TopBar/index.jsx, src/containers/Dashboard.js, src/containers/TopBar.js, src/css/application.css
Moves the snapshot button to the top bar. Not much more to say about it.
Another step in #779
=> Move snapshot button to top bar

src/css/application.css
* Add top margin, same as bottom, to create space between first notification and top bar
* Less padding around X
* Don’t allow top bar to shrink when notifications appear
Goes to #779
=> Tweaks to notification UI

src/selectors/getEnabledLibraries.js
If there is no current project, there are no enabled libraries.
Fixes #980
Fixes #981
=> Don’t assume non-null current project when selecting enabled libraries

locales/en/translation.json, package.json, src/actions/index.js, src/components/Dashboard.jsx, src/components/ProjectList.jsx, src/components/ProjectPreview.jsx, src/components/TopBar/NewProjectButton.jsx, src/components/TopBar/ProjectList.jsx, src/components/TopBar/ProjectsButton.jsx, src/components/TopBar/index.jsx, src/components/index.js, src/containers/Dashboard.js, src/containers/ProjectPreview.js, src/containers/TopBar.js, src/containers/index.js, src/css/application.css, src/reducers/ui.js, src/selectors/getActiveSubmenu.js, src/selectors/getAllProjectKeys.js, src/selectors/getProject.js, src/selectors/index.js, src/selectors/isUserAuthenticated.js, src/selectors/makeGetProjectPreview.js, src/util/generatePreview.js, test/unit/reducers/ui.js, yarn.lock
This completes the composition of the top bar:
Along with this move, also made a couple of improvements to performance. First, used the memoized selector factory pattern to ensure that we don’t unnecessarily re-render project previews when unrelated things in the environment change. Also refactored the preview generation itself so that it doesn’t do unnecessary extra work aside from just parsing the document and grabbing the title.
Goes to #779
=> Move New Project and Load Project into top bar

src/components/EditorContainer.jsx, src/components/EditorsColumn.jsx, src/components/Output.jsx, src/components/Sidebar.jsx, src/components/Workspace.jsx, src/css/application.css
Editor labels are moved to the top-right, lighter color scheme, no transparency, and no rounded corners. Also chevrons.
When clicked, the editor is minimized. Minimized editor appears as a bar at the bottom of the editors column, basically a full-width version of the editor label, with no actual editor. The chevron points up. Clicking this bar expands the editor.
This did involve removing the label on the output, which does not exist in the redesign. This means that there is now no way to minimize the output. I think that might be okay since you can now drag the column divider to give the editors more space, although ideally it would be good to still be able to fully minimize it.
=> Overhaul editor labels and show/hide

src/components/Preview.jsx, src/css/application.css
Project preview now has a title bar at the top, which displays the project title, as well as the refresh and pop-out buttons.
Goes to #779
=> Add title bar to project preview

src/components/PreviewFrame.jsx, src/css/application.css
Fun fact: [you can’t use `top`/`left`/`right`/`bottom` to size an absolutely-positioned iframe!](https://www.w3.org/TR/CSS21/visudet.html#abs-replaced-height).  You need to give iframes explicit `height` and `width`, full stop.
The solution is pretty simple—add a container `<div>` that we size using the absolute position boundaries, then give the iframe a `height` and `width` of 100%.
Fixes #989
Fixes #990
=> Use container div to correctly size preview iframe

src/sagas/ui.js, src/util/index.js, test/unit/sagas/ui.js
Chrome no longer supports navigation to data URIs in the top level window, for security reasons. So, for the preview as well as the spinner that is displayed until gist export completes, we instead populate the new window using good old `document.write`.
There is a minor concern here about security—in particular, we don’t want malicious imported code to be able to access the Popcode environment and attempt to e.g. hijack the user’s GitHub session.  I *think* the implementation herein prevents such an attack by removing the `opener` property on the new window before populating its content, in principle making it impossible for the opened window to access the Popcode environment. This approach is discussed e.g. [in a Chromium thread discussing `window.opener` security …
=> Don’t navigate to data URIs at the top level

package.json, src/clients/github.js, src/components/Dashboard.jsx, src/containers/Dashboard.js, src/css/application.css, src/records/Project.js, src/reducers/projects.js, src/selectors/getCurrentProjectInstructions.js, src/selectors/getProjects.js, src/selectors/index.js, yarn.lock
Implements https://github.com/popcodeorg/popcode/issues/780!
Notes:
- I went with the [remark](http://remark.js.org/) markdown->react library because it looks like it's being used in https://github.com/popcodeorg/popcode/pull/861.
- Adds markdown file import&export to the gist and snapshot features, but does not add it to the proposed repo export feature (this should be trivial though).
- Makes order of all file concatenation deterministic (including for CSS & JS, this seemed like a good idea).
Some sample gists if you want to check them out on the branch:
[Gist with small markdown sample](https://gist.github.com/inlinestyle/f72628405e55bea43267ed91f0bb92dc)
[Gist with long markdown sample](https://gist.github.com/inlinestyle/b2b6a8fa00f160e00ccf9ca0c1895994)
=> Project README

package.json, src/templates.js, src/util/generatePreview.js, yarn.lock
Only one remaining place used data URIs, and it wasn’t particularly
necessary—link tags to include CSS libraries in the header. Instead just
use a `<style>` tag and inline the CSS.
Fixes #997
=> Remove remaining use of data URIs

src/components/TopBar/HamburgerMenu.jsx, src/css/application.css
I noticed this during training and it bothered me.
Before:
After:
=> Fix unecessary ugly scrollbar in hamburger menu

package.json, src/validations/css/prettycss.js, test/unit/validations/css.js, yarn.lock
Fixes bug https://github.com/popcodeorg/popcode/issues/584
Gave commas between CSS parenthesis statements like `rgba` leeway in the PrettyCSS validation.
I found that doing so inadvertently created another bug where multiple commas would flag as valid. I added another check to deal with this as well as added the requisite validations in the test case.
=> Fix #584 text-shadow with multiple values

src/components/TopBar/ProjectPicker.jsx, src/components/TopBar/createMenu.jsx
Followup to #1016 based on post-merge code review:
* Better parameter name for wrapped component in `createMenu`
* Remove unused second argument to `createMenu` in `ProjectPicker` component
=> Code improvements to click-outside

.travis.yml, gulpfile.js, karma.conf.js, package.json, webpack.config.js, yarn.lock
Step 1 of N in reducing the size of the initial bundle load. This removes non-English `moment` locales (since English is currently the only supported localization across the application). Trims bundle size by about 7%.
Also adds `source-map-explorer`, which is proving to be a really useful tool for tracking down the biggest contributors to bundle size.
Relevant to #348
=> Reduce bundle size a bit

src/css/application.css
Makes 3 style improvements, including one suggested by https://github.com/popcodeorg/popcode/issues/1032. Thanks @jwang1919 for the test gist!
1. ([gist](https://gist.github.com/inlinestyle/882e2a262c80045163efca50e519f34f))  Constrain width of images
2. ([gist](https://gist.github.com/inlinestyle/882e2a262c80045163efca50e519f34f)) Constrain width of code blocks via `whitespace: pre-wrap` (both visible code blocks are wrapped on the second line)
3. ([gist](https://gist.github.com/jwang1919/ca79bdb9b543ae6e6bac57d28e14c1cf)) Vertically center inline code fragments and prevent them from bleeding into adjacent lines of text
=> Styling tweaks to instructions markdown

gulpfile.js, locales/en/translation.json, package.json, src/components/CopyToClipboard.jsx, src/components/notifications/SnapshotNotification.jsx, src/init/ZeroClipboard.js, src/init/index.js, yarn.lock
Many classrooms use browser versions that are too old to support the native clipboard API. While `copy-to-clipboard` falls back directly to showing a prompt, we can provide a better UI for most older browsers by falling back to `ZeroClipboard`, which uses Flash to create a seamless copy-paste experience.
From a user standpoint, the ZeroClipboard workflow is exactly the same as the modern browser workflow. If ZeroClipboard is unavailable, we then finally fall back to the prompt approach.
Fixes #1038
=> Fall back to ZeroClipboard if native clipboard API is unavailable

config/browsers.json, package.json, src/components/EditorContainer.jsx, src/components/EditorsColumn.jsx, src/components/Output.jsx, yarn.lock
We are changing flex-related values in JavaScript, but we support browsers that only take flex properties with vendor prefixes. So, use the `inline-style-prefixer` library to add appropriate vendor prefixes to the JavaScript style objects.
Also drop support for Chrome 22, which additionally has an outdated and overly strict interpretation of percentage heights that breaks Popcode’s layout. Happily, Chrome 23 works fine. According to Google Analytics, Popcode has only been loaded once using Chrome 22 since May 1, and I’m guessing this was me in BrowserStack.
=> Fix dynamic flex in older browsers

locales/en/translation.json, package.json, src/validations/html/htmllint.js, yarn.lock
We had to temporarily roll `htmllint` back to version 0.5.0, because we discovered that when using the latest version, the interpreter will [lock up under certain circumstances](https://github.com/htmllint/htmllint/issues/209). Having dug deeper, I narrowed the issue down to a new rule, `attr-validate`, which can encounter catastrophic backtracking with the right invalid attribute.
By disabling `attr-validate`, we can go back to using latest `htmllint` without problems. However, I went a step further and future-proofed our `htmllint` validator by automatically disabling all rules that we don’t explicitly enable to use for validation. Thus we won’t get caught by a novel, default-enabled rule in the future.
Finally, while I was in there, set up a couple of new `htmllint` validations:
* …
=> Restore latest htmllint, disable rules by default

src/css/application.css
Generally when we zoom in on Popcode, it’s because we need to see the editor/output more clearly. Expanding the size of the top bar just takes up valuable space.
So, use “one weird trick” to keep the top bar from growing: specify the base font size for the `top-bar` container in `vh` rather than `px`.  Since the rest of the top bar sizing is built around the base font size, the top bar stays the same size regardless of zoom.
Note that this doesn’t work in very old browsers, although it does work in Chrome 38, which is the oldest Chrome version that sees substantial usage with Popcode. It also doesn’t work in Safari. However in browsers where it doesn’t do what we want, it degrades gracefully (it looks fine normally, and the top bar still expands when you zoom in).
=> Prevent top bar zoom

.travis.yml, gulpfile.js, package.json, yarn.lock
`NODE_ENV` should be set to `production` in the actual environment, rather than relying on `yargs` in Gulp to take care of it. That way the env is consistent across the entire build, and we don’t need to depend on the order in which things run.
=> Set NODE_ENV in actual environment

gulpfile.js, karma.conf.js, webpack.config.js
I went ahead and implemented the changes I discuss in [this comment](https://github.com/popcodeorg/popcode/pull/1031#issuecomment-335047209) so you can see exactly what I'm talking about!
In this branch, `webpack.config.js` exports a function that accepts an `env` parameter. You can pass `'development'`, `'production'`, or `'test'`. The webpack configuration gets modified depending on the environment. The behavior is almost exactly the same on this branch—in `'test'` mode, the `devtool` property is `inline-source-map` and `source-map` otherwise. The one difference is that now we only add the `UglifyJsPlugin` when `env === 'production'`. This shaved a minute-and-a-half off build time in development for me.
Let me know what you think! This would solve some of the issues I brought up in …
=> Convert webpack.config.js to export a function

gulpfile.js
Forgot to change one of the usages of `webpackConfiguration` in the gulpfile! This fixes that. Sorry to anyone who got `yarn dev` errors.
=> Update webpack invocation in browserSync gulp task

.eslintrc, package.json, yarn.lock
We only added ajv to `package.json` dependencies because of a Webpack bug which has now been fixed.
Upgrades all dependencies to semver latest. Tested application and all seems to work well!
=> Upgrade semver dependencies and remove explicit ajv

package.json, webpack.config.js, yarn.lock
Many packages (notably Firebase) come with pre-compiled/minified code, with sourcemaps shipping alongside. The `source-map-loader` integrates the pre-packaged sourcemaps into the final bundle’s sourcemaps, giving us better visibility into what’s going on in library code.
=> Integrate source-map-loader

src/util/generatePreview.js
This probably wasn’t intentional, but [`append()`](https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/append) is a fairly new/experimental DOM API method that is only supported by very new browser versions.
Instead, use `appendChild`, which was invented during the Big Bang.
Fixes #1036
Fixes #1063
=> Use appendChild rather than append

.eslintrc, package.json, src/validations/importLinters.js, webpack.config.js, yarn.lock
`System.import()` never made it into real JavaScript and was long ago deprecated in favor of `import()`. Finally migrate to the correct syntax, by switching to using the `babel` parser for `eslint`, and also adding the `syntax-dynamic-import` Babel plugin.
=> Use modern dynamic import syntax

package.json, yarn.lock
Only [breaking change](https://github.com/i18next/i18next/blob/master/CHANGELOG.md) has something to do with Portuguese, so we should be good.
=> Upgrade i18next

src/actions/projects.js, src/reducers/projects.js, src/sagas/projects.js, test/unit/reducers/projects.js, test/unit/sagas/projects.js
Completely unnecessary inefficiency when loading projects from Firebase: we were iterating over each project and dispatching a separate `PROJECT_LOADED` action for each one. This caused N discrete Redux store updates, and thus N discrete React state updates, for N projects loaded.  Resulted in a definitely noticeable lag when loading projects into my workspace.
Instead, switch to a `PROJECTS_LOADED` action which adds all projects to the Redux store in a single dispatch.
Might help with (but probably won’t fix) #1117
=> Add all loaded projects to store in single Redux action

src/util/Bugsnag.js
Bugsnag got that feature at some point, so there’s no need to hand-roll an event listener.
=> Use built-in unhandled rejection notifications in Bugsnag

src/util/Bugsnag.js
E.g. `firebase/auth` is minified and does not have a sourcemap, so the file numbers in stacktraces that include `firebase/auth` are meaningless and change with each release. So, for stacktraces that include stack frames in `firebase/auth`, we want to ignore the stacktrace and just group based on the error. This will allow us to more effectively ignore a couple of errors that come from `firebase/auth`, generate a lot of noise, but do not seem to have any user-facing effect.
Fixes #1115 
Fixes #1114 
Fixes #1095 
Fixes #1035 
Fixes #1092 
Fixes #1111 
Fixes #1110 
Fixes #1120 
Fixes #1089 
Fixes #1020 
Fixes #1116 
Fixes #1100 
Fixes #1093 
Fixes #1096 
Fixes #1091 
Fixes #1090 
Fixes #1037 
Fixes #1066 
Fixes #1057 
Fixes #1051
=> Group Bugsnag errors by message when stacktrace includes minified files

src/components/TopBar/ProjectPicker.jsx, src/components/TopBar/index.jsx
Previous logic was to show the project picker if there were at least two non-pristine projects in the workspace. Seems reasonable—why show a project picker if there aren’t multiple projects to choose between?
The problem is that the project picker only shows non-pristine projects (projects we have saved), so there is a bug:
1. In a Popcode session, log in and create a project, which is auto-saved.
2. In a later Popcode session, log back in.
3. Because it’s a new session, you are looking at  a new (pristine) project. There is exactly one saved project in the workspace.
4. So, the picker does not appear, because it requires at least two saved projects.
So, instead, show the project picker as long as:
* The user is logged in
* There are *any* non-pristine projects
As well as fixing the bug …
=> Always show project picker when user is logged in

src/containers/TopBar.js
No reason to report this to Bugsnag—just show the user an error message
and prompt to try again.
Fixes #1118
Fixes #1119
Fixes #1041
=> Catch Firebase auth/internal-error silently

src/validations/html/htmllint.js
For [certain sequences of inputs](https://github.com/htmllint/htmllint/issues), an `htmllint` linter instance will produce false positive errors for a valid final input. I didn’t dig into exactly why, but it’s clearly retaining some kind of state that it shouldn’t be.
So: just instantiate a new `Linter` instance for each pass.  Unfortunately the `Linter` constructor isn’t _totally_ trivial, but it doesn’t appear to do anything particularly slow, so hopefully this should be fine from a performance standpoint.
Fixes #949
=> Create new htmllint.Linter instance for each run

src/channels/loginState.js, src/clients/firebase.js, src/sagas/user.js, test/unit/sagas/user.js
Channels aren’t allowed to emit `null` or `undefined`, so simply wrap the `userCredential` emitted by `onAuthStateChanged` in an object with a single `userCredential` key, which itself may or may not be null.
Fixes #1153
=> loginState channel emits object wrapper for userCredential

src/components/PreviewFrame.jsx
Was passing in a first argument corresponding to the error language, but the signature of the handler function changed, no longer taking that argument. Remove it and runtime errors are back in business.
=> Fix runtime errors

src/clients/firebase.js, src/util/Bugsnag.js
There has been a longstanding issue where, if a slow network condition occurs during signing, Firebase will not only reject the sign in promise but also throw an uncaught global network error. This has historically been very noisy in Bugsnag.
So, set up some armor plating around it—specifically, if during the course of Firebase sign-in there is a global error whose message case-insensitively contains the string “network error”, we ignore the global error.
Also, revert the previous attempt to deal with these annoying errors, namely code that tries to vary error grouping logic based on the backtrace.  This was premised on the idea that we know the sourcemapped backtrace of the error in the application environment, which is of course entirely incorrect (unless dev tools happen to be open), …
=> Catch uncaught errors during Firebase auth

src/reducers/errors.js
When we import a snapshot, we validate the code, which is correct—however, this was not reflected in the `errors` state, which was not set to `validating` for that period. So, right when a snapshot came in, the UI attempted to render it before validation had completed. In the case where e.g. JavaScript had syntax errors, this would cause the preview to throw an exception, causing the entire application to crash.
Fix the issue by properly setting the validation state on snapshot import, preventing the preview from attempting to render.
=> Set error state to validating when snapshot is imported

locales/en/translation.json
Resolves issue #1101...
CSS error should include the symbol for semicolon ;
=> Resolved: CSS error should include the symbol for semicolon

src/css/application.css
Modified styles to prevent zooming on the entire workspace.
This uses a similar strategy employed in the TopBar to prevent zooming in on other page elements, making it easier to see the code when presenting.
=> No Zoom Workspace

src/components/PreviewFrame.jsx
In production the `load` handler is never firing; it’s hard to tell why for sure, but one possibility is that the frame is loading before we get the `ref` and attach the handler. So, always set the `src` initially to `about:blank`, and then in the `ref` callback set the `srcdoc` to the actual preview contents *after* attaching the load listener.
Should guarantee that the load listener fires.
=> Explicitly set preview srcdoc after attaching load handler

src/css/application.css
Some style tweaks to the application chrome (specifically the code labels and preview header). Not only adds some general style finesse, but also makes the code labels smaller and slightly translucent, making them a bit less intrusive (https://github.com/popcodeorg/popcode/issues/1002). The styles also generally respect the updates coming to the top bar. (https://github.com/popcodeorg/popcode/pull/1181).
- Made the code labels font-size smaller (matches new top bar style)
- Added a subtle shadow to code labels and preview header (matches new top bar style)
- Added a bottom rounded corner to code labels (matches new top bar style)
- Made the code labels background slightly translucent
- Made the code labels width automatic.
=> Updated chrome styles.

src/reducers/compiledProjects.js
If you create a new project, or start the process of switching to an existing project, we want to clear the preview state. Otherwise:
* When you create a new project, the old project sticks around
* When switching projects, the preview is unpleasantly flashy between old and new state
Fixes #1204
=> Clear compiled projects when a project is created or switched to

bower.json
Upgrades from jQuery 2.2.3 to jQuery 3.2.1. This is a major version upgrade with [numerous breaking changes](https://jquery.com/upgrade-guide/3.0/), but none of them look like they would have any overlap with the kind of jQuery students write in Popcode. In fact, the only thing that even comes close is the behavior of `show()`, which is in fact the proximate motivation for this upgrade: calling `show()` on an element that was hidden with a CSS tag selector inside a sandboxed iframe threw an error in jQuery 2. Now it just sets its `display` value to `block` (regardless of whether this is the correct `display` for the element in question).
Fixes #581
Fixes #1190
=> Upgrade to jQuery 3.2.1

src/actions/compiledProjects.js, src/actions/index.js, src/actions/ui.js, src/containers/Preview.js, src/reducers/compiledProjects.js, src/reducers/errors.js, src/reducers/ui.js, src/sagas/compiledProjects.js, src/selectors/getLastRefreshTimestamp.js, src/selectors/index.js, src/util/generatePreview.js, test/unit/reducers/ui.js, test/unit/sagas/compiledProjects.js
Fixes a recent regression in the refresh button and adds functionality that has always been missing.
The regression: the refresh button stopped working entirely. Previously we refreshed the preview by artificially adding the idea of a “last refresh timestamp”, which was given as an argument to the preview generator, causing its output to change and thus the preview iframe to refresh.
Things work differently now.
Since the preview now has first-class state, all we need to do is add a copy of the current compiled project to the stack of compiled projects, which triggers the desired refresh behavior in the Preview component.
The always-missing feature: runtime errors are now cleared when you refresh the project.
Fixes #1212
=> Fixes for refresh button

locales/en/translation.json, src/validations/html/htmlInspector.js, test/unit/validations/html.js
Closes #1178 
This is a common student mistake I see, which is that students forget to write `<li>` inside their lists, and therefore don't actually get what they expect. I've added an error message for this use case, because for the purposes of teaching this is the only valid syntax we should expect.
Example of the error message:
=> Error message for lists (ul, ol, dl) with text children #1178

package.json
This mainly affects local development. I checked that the travis config is already installing exact versions of these dependencies, so no change is needed there.
Closes #1193
=> Update package.json to allow differences in minor version of node, yarn

src/html/index.html
Hi, I am adding four `<link rel="dns-prefecth">`. Issue #1199.
Links point to GitHub, Google Analytics and Google APIs. I check the Network tab and see Popcode interacting with their domains. 
I'm omitting Firebase for now because I'm not sure which domain to use.
Fixes #1199
=> Add dns-prefetch links

src/components/TopBar/CurrentUser.jsx
Hello, I remove login `<span>` and move its event listeners into parent `<div>`. Issue #1222
A couple observations:
- `<div>` is the login button, but its click area was limited to its child `<span>`.  To fix this, I move `<span>`'s event listeners into `<div>`.
- `<span>` has a class `top-bar__log-in-prompt`, but I don't see that class defined anywhere. That's why I didn't add the class to `<div>`.
=> Enlarge login button target area

.travis.yml, package.json, webpack.config.js, yarn.lock
Two problems with linters.js, possibly related:
* No minification
* Had ES6 code
Fixed both issues, and also fail the build if JS build artifacts can’t be parsed as ES5.
=> Fix production build of linters.js

src/sagas/compiledProjects.js
This PR closes [issue 1257](https://github.com/popcodeorg/popcode/issues/1257).
It's also my first Popcode PR 🎉 Validating the source on project creation made sense to me but feedback is welcome as I learn more about the code base :)
=> Validates source on project creation, closes #1257

src/components/PreviewFrame.jsx
Closes #1254.
Followed the advice on the issue: prevent the app from crashing first by stringifying the value and worry about pretty printing in #1252. Still thought a bit about how we'll accomplish that and have some links I'll share on the latter issue...
=> Stringifies console value in preview frame, closes #1254

src/components/PreviewFrame.jsx, src/previewSupport/createScopedEvaluationChain.js, src/previewSupport/handleConsoleExpressions.js
We want console statements to be evaluated such that each statement is evaluated in the context of all the previous statements, but variables defined in the console are _not_ global variables (i.e. they should not be accessible from the project’s JS code).
Creates a `createScopedEvaluationChain` which does some fancy footwork to evaluate each statement, return the value, and also yield a function that will evaluate the next statement in the context created by the last one.
Closes #1266
=> Scoped evaluation of console statement

src/components/Console.jsx, src/css/application.css
Console now scrolls like most other consoles: once there are enough entries to overflow the available space, the extra entries overflow the top of the viewport, with the input stuck to the bottom. You can scroll up to see older entries.
Implemented with a fairly bananas feature of Flexbox, `flex-direction: column-reverse`, which just basically turns the contents of the flex container upside down.
Closes #1251
=> Improved scrolling behavior for console

src/components/ConsoleInput.jsx, src/components/Editor.jsx, src/css/application.css, src/util/ace.js, src/util/createAceSessionWithoutWorker.js
E.g. if the student types `{` and presses enter, that should be that.
Extracts the creation of an ACE editor with universal defaults into a module.
Fixes #1253
=> Don’t auto-close in the console input

src/css/application.css
* Open up the line height for headers and paragraph/list item text
* Remove padding from `code` blocks inside list items (as we already do for `code` inside paragraphs)
* Add a bit of bottom margin to list items
=> Readability improvements for instructions

src/components/EditorsColumn.jsx, src/components/Instructions.jsx, src/components/Output.jsx, src/css/application.css
We want the `main` area of the screen to fill up all available vertical space not needed by the navigation bar, but no more. The instructions pane should use the vertical space afforded by its parent, but no more; if it needs more space, it should scroll internally.
Previously we were simply setting the instructions to `overflow: auto` and crossing our fingers. Chrome interpreted this the way we wanted—keep the instructions the same height its container naturally wants to be from flex. However Firefox allowed the instructions to get as big as they needed to based on content size, pushing the `main` to be bigger than the way it flexed naturally.
So, add a layer of nesting in the instructions panel; the outer div takes the height of its container via the default `align-items: stretch` in …
=> Ensure instructions fit within container

src/actions/console.js, src/actions/index.js, src/components/Preview.jsx, src/components/PreviewFrame.jsx, src/containers/Preview.js, src/preview.js, src/previewSupport/handleConsoleLogs.js, src/records/ConsoleEntry.js, src/reducers/console.js, test/unit/reducers/console.js
In the preview frame, we capture console.log and its cousins and send the output to the Popcode console, before deferring to the browser implementation.
For now we treat all of these functions exactly the same - console.log is the only one used in the ScriptEd curriculum as far as I know.
Fixes: #1249
=> Evaluate console.(log, debug, etc) and send to the Popcode console

package.json, test/unit/validations/javascript.js, yarn.lock
JSHint 2.9.5 freezes when given certain invalid/incomplete for loop syntax. This appears to be a regression in the latest patchlevel and is fine in 2.9.4. Downgrade until the problem is fixed.
Fixes #1227
=> Downgrade jshint to 2.9.4

config/browsers.json, gulpfile.js
No reason we can’t support Chromium; Bowser considers it different from Chrome. So, add Chromium to the browser support list.
It’s stripped out when passing to `cssnext` as `browserslist` doesn’t consider Chromium a separate browser.
Fixes #1177
=> Support Chromium

src/config.js
Someone seems to be running a downloaded copy of Popcode in production mode, which generates a bunch of noisy errors in Bugsnag. So, update the notifier key to get rid of them.
=> Rotate Bugsnag API key

locales/en/translation.json, src/actions/compiledProjects.js, src/actions/index.js, src/reducers/ui.js, src/sagas/compiledProjects.js, test/unit/reducers/ui.js, test/unit/sagas/compiledProjects.js
In at least one known case, projects currently fail to compile because of a downstream error in `recast`. In general since it is possible for project compilation to throw an uncaught error, we want to catch those errors, display a useful error message, and report the error to Bugsnag. This does that.
Offers a partial fix for #1192
=> Gracefully handle compilation failures

src/components/Console.jsx, src/containers/Console.js
If we completely remove the console component any time the project is not in a known valid state, the console will be unmounted and remounted every time the user types a keystroke in an editor (since this puts it in a `validating` state for at least a split second). This is undesirable for several reasons, including that the console input is focused on mount (meaning it steals focus when the user is typing in a code editor); and that setting up and tearing down an ACE editor on each keystroke is a huge waste of runtime resources.
Fixed by just `display: none`ing the console component when it should not be visible.
Fixes #1325
=> Hide console when errors visible rather than removing it

src/components/Console.jsx, src/components/ConsoleEntry.jsx, src/components/ConsoleExpression.jsx, src/components/ConsoleInput.jsx, src/components/ConsoleOutput.jsx, src/css/application.css
* Adds chevrons to console input and output. Input row displays a blue right-facing chevron. Entered expression displays a gray right-facing chevron. Expression value displays a gray left-facing chevron. Values produced by `console.log()` have no chevron, but the same indentation.
* Adds a border and some padding between entries.
Closes #1312
=> Console chevron and border

src/components/PreviewFrame.jsx
Preview frames can call `error` and `log` over JSChannel, which the `<PreviewFrame>` component listens for. However, these messages should be ignored unless the frame that sent them is the currently active preview frame. Fixes a bug where console log messages would appear duplicated after reloading the environment.
Fixes #1326
=> Ignore messages from inactive preview frames

package.json, src/components/PreviewFrame.jsx, src/css/application.css, src/previewSupport/handleConsoleExpressions.js, src/previewSupport/handleConsoleLogs.js, src/previewSupport/prettyPrint.js, yarn.lock
Gets us marginally nicer pretty printing behavior for console output, using `object-inspect`. This is an improvement over JSX in that:
* Objects are formatted with some helpful whitespace
* Object keys are not quoted
* Functions are printed meaningfully (just shows e.g. `[Function f]` but much better than `JSON.stringify` which does nothing at all!)
* DOM nodes are printed quite nicely
Quick first pass at #1252
=> Basic pretty printing for console

.travis.yml, karma.conf.js
In response to the Spectre/Meltdown vulnerabilities, Chrome made a change which [caused a regression on Travis preventing Chrome from running in container-based infrastructure](https://github.com/travis-ci/travis-ci/issues/8836).  This [can be worked around in a couple of ways](https://docs.travis-ci.com/user/chrome), including adding a `sudo: true` configuration to Travis, which switches the project back to the older infrastructure in which each build spins up its own VM.
That older infrastructure takes longer to build (because you have to spin up a full VM), so we prefer to stick with the container-based architecture. Accordingly, for CI builds we will run Chrome with the `--no-sandbox` flag, which allows it to run without `sudo`.
=> Work around Chrome sandbox error on Travis

src/components/PreviewFrame.jsx, src/previewSupport/prettyPrint.js, src/util/javascript.js, src/validations/css/css.js, src/validations/css/prettycss.js, src/validations/css/stylelint.js, src/validations/html/htmlInspector.js, src/validations/html/htmllint.js, src/validations/html/slowparse.js, src/validations/javascript/esprima.js, src/validations/javascript/jshint.js, test/unit/util/javascript.js, webpack.config.js
Specifically, whitelists expression statements whose expression is assignment, an identifier, a literal (i.e. `undefined`), or a member expression (e.g. `obj.foo`, `arr[0]`).
Testing caveats: for some reason, the console answers never appear when I run via `yarn dev`. The answers appear from `yarn preview`, but I have to open the server in incognito mode for the `preview.js` to refresh. For `preview.js` to refresh in my normal browser session, I had to `rm -rf dist static/compiled bower_components node_modules`; not sure which directories actually cleaned up my browser session's `preview.js`.
Therefore, this PR may be incomplete; let me know how to improve testability!
=> Print undefined for certain entries; fixes #1333

src/actions/clients.js, src/reducers/projects.js, src/sagas/projects.js, test/unit/reducers/currentProject.js, test/unit/reducers/projects.js, test/unit/sagas/projects.js
Previously the project key was retained through both project imports and exports, making it possible for a descendant of a project to overwrite the original (see fixed issue for details).
Instead, the `snapshotImported` action’s payload contains both a generated project key and the project data from the snapshot. The project key, which is generated in the saga, is always used when adding the project to the store (overwriting the original `projectKey` in the stored snapshot data).
Fixes #1341
=> Always give imported snapshot new project key

package.json, src/previewSupport/overrideAlert.js, yarn.lock
I would like to propose to switch from SweetAlert to [SweetAlert2](https://github.com/sweetalert2/sweetalert2) - the supported fork of SweetAlert. The original reason for creating SweetAlert2 is inactivity of SweetAlert: https://stackoverflow.com/a/27842854/1331425 
1. Accessibility (WAI-ARIA) - SweetAlert2 is fully WAI-ARIA compatible and supports all popular screen-readers. Accessibility is a must in 2017, there are a lot of explanatory and tech articles, but this one is truly inspirable: [Software development 450 words per minute](https://www.vincit.fi/en/blog/software-development-450-words-per-minute/)
2. Better buttons contrast is a huge advantage for all users especially for users with vision disabilities. 
3. Better support, average time to resolve an issue:
- SweetAlert: …
=> Switch from SweetAlert to SweetAlert2

src/components/Instructions.jsx
We already return 'null' if 'instructions' is falsey, so no need to
do it in JSX too.
=> Remove redundant null-check from Instructions.jsx

src/sagas/errors.js, src/validations/css/css.js, src/validations/css/prettycss.js, src/validations/css/stylelint.js, src/validations/html/htmlInspector.js, src/validations/html/htmllint.js, src/validations/html/slowparse.js, src/validations/index.js, src/validations/javascript/esprima.js, src/validations/javascript/jshint.js, test/unit/sagas/errors.js
For reasons I’m no longer totally clear on, we asynchronously loaded each linter library discretely. Instead, just load the entire validations module when needed, substantially reducing the footprint of asynchronous loading, and also allowing the validations module to be tested without needing to do async loading in a test environment (which anyway seems weird for unit tests).
=> Move async loading of validations to saga

package.json, webpack.config.js, yarn.lock
Upgrades all dependencies to semver-compatible latest.
Also upgrades Karma and removes lots of unnecessary Webpack plugins from the test Webpack configuration. None of this ends up mattering but were attempts to fix an issue with running tests that pulled in async modules. Ultimately I just refactored the code so unit tests don’t have to do that. But the changes to the test configuration were sensible so I’m leaving them in.
=> Upgrade all semver-compatible dependencies

.eslintrc, package.json, test/index.js, test/unit/validations/html.js, webpack.config.js, yarn.lock
Also adds support for implicitly loading `.mjs` modules.
=> Upgrade array-to-sentence library to 2.0.0

src/util/compileProject.js
In Chrome 38, DOM collections have particularly buggy behavior with respect to iteration—specifically, `Symbol.iterator in domCollection` evaluates to `true`, but `domCollection[Symbol.iterator]` is undefined!  This bug is [mentioned in a `core-js` issue from around that time](https://github.com/zloirock/core-js/issues/37#issuecomment-75811905).
Transpiled array destructuring uses iteration in its implementation, and thus breaks when attempting to destructure a DOM collection in the affected Chrome version(s). Because of the inconsistent feedback given by the runtime, `core-js` isn’t able to effectively polyfill iteration on this version.
So, just don’t destructure DOM collections—instead, do it the old fashioned way.
Fixes #1338
=> Don’t destructure DOM collections

package.json, yarn.lock
Upgrades the following dependencies in the Webpack ecosystem:
* `exports-loader`
* `html-webpack-plugin`
* `imports-loader`
* `string-replace-loader`
* `webpack-dev-middleware`, but only to to 2.0.6, since later versions have a peer dependency on Webpack 4 (see below)
Also removes `webpack-hot-middleware` which we don’t actually use.
One notable absence here is `webpack` itself—unfortunately not all of the Webpack loaders/plugins we use are ready for Webpack 4, plus the documentation seems to be really bad at this point. Will try again in April.
=> Upgrade Webpack-related dependencies

package.json, src/validations/html/runRules.js, yarn.lock
Requires explicitly importing the `sax` module, which is otherwise loaded lazily and marked as only being available in Node (despite working fine in the browser).
=> Upgrade parse5 to latest

.travis.yml
Based on exceptions that Bugsnag is reporting, it seems like the tests on Travis are being run with a `NODE_ENV` of production, even though the Karma configuration should be propagating `test` through the Webpack env plugin. Anyway, it’s probably more sensible to just explicitly set the environment variable when running tests.
We do keep the env variable set to `production` for the rest of the Travis run since that’s the correct value for building the production bundle that’s going to get deployed.
=> Explicitly set test NODE_ENV for running tests on Travis

package.json, src/services/appFirebase.js, yarn.lock
Running `yarn` has generated a bunch of warnings about peer dependencies for a little while now, which isn’t a great look. This pull request fixes them:
* Adds `caniuse-lite` as an explicit dependency to satisfy the peer dependency of `autoprefixer`
* Switches to using a la carte Firebase packages for the components of Firebase that we actually use, and adds one other package, `@firebase/app-types`, as an explicit dependency to satisfy the peer dependency of the others
The latter change should hopefully result in a smaller bundle as well!
=> Fix peer dependency warnings

package.json, src/validations/javascript/esprima.js, yarn.lock
Upgrades esprima to 4.0.0. This required switching from a default import to named imports, which somehow stymied me for months, but I’m pretty sure was all we needed to do the whole time.
=> Upgrade esprima

package.json, src/util/markdown.js, yarn.lock
Runs instructions markdown through `remark-external-links`, which by default adds a `target="_blank"` and `rel="noopener noreferrer"` to anchor tags.
At this point this is hard-coded into the `toReact` method used here, with no option to disable it—could always make it optional in the future, but it’s hard to imagine a situation in which we wouldn’t want links from processed Markdown to open in a new window.
=> Links from instructions open in a new window

src/clients/github.js, src/components/TopBar/HamburgerMenu.jsx
GitHub will shortly be [removing the ability to do anonymous gist export via their API](https://blog.github.com/2018-02-18-deprecation-notice-removing-anonymous-gist-creation/).  So, only show the **Export Gist** button if you’re logged in. The GitHub client now assumes you’re authenticated when doing a gist export, which allows us to trim some no-longer-needed code.
Fixes #1363
=> Remove anonymous gist export

src/actions/projects.js, src/components/InstructionsEditor.jsx, src/components/TopBar/LibraryPicker.jsx, src/components/TopBar/ProjectPicker.jsx, src/components/TopBar/createMenu.jsx, src/css/application.css, src/reducers/projects.js, src/sagas/projects.js, test/unit/reducers/projects.js, test/unit/sagas/projects.js
1. Focus on the instructions editor when it mounts (if there are no instructions yet.)
2. Add a placeholder for the instructions editor `textarea`.
3. Use the code editors' monospace font for the instructions editor.
4. Rename the `isEnabled` `MenuItem` `prop` to `isActive`.
One thing I didn't notice until today—because of the way I implemented the action/reducer logic for the instructions editor, edits to the instructions don't update the `project.updatedAt` field. This means that if you load a fresh project, spend a bunch of time editing the instructions _without touching anything else_, and then accidentally refresh the page, you'll lose your work. Should the instructions editor be part of the "grace period" flow? I think changing that would be trivial.
Also, should I implement the …
=> Follow-up polish for Instructions editor UX

src/components/Workspace.jsx, src/util/queryParams.js, test/unit/util/queryParams.js
Factor our functions dealing with the url query parameters to a
helper module
Fixes: #1358
=> Preserve experimental flag (and only experimental) after refresh

src/components/Console.jsx
closes #1348
The console was not being hidden during the error state, because the `u__hidden` class was applied to the wrong element.
=> Hide console during error state

src/components/PreviewFrame.jsx
closes #1176
Adds `allow-popups-to-escape-sandbox` to the preview's iframe, so that links with `target="_blank"` will open correctly.
=> Add allow-popups-to-escape-sandbox token to PreviewFrame

package.json
`yarn preview` will run a server hosting Popcode compiled in the same way it is for production. Particularly useful for testing changes to Webpack configurations etc.
A couple of improvements:
* Runs preview on port 3000, matching normal BrowserSync behavior
* Only removes the *contents* of `dist` before building (needed to work on Docker)
=> Improvements to development preview script

gulpfile.js, karma.conf.js, package.json, src/util/compileProject.js, webpack.config.js, yarn.lock
Webpack 4 is a major upgrade that substantially improves build performance and asset size. It comes with more built-in behavior and reasonable defaults.
It also has no discernible documentation.
This PR upgrades us to Webpack 4; major combat operations include:
* Upgrade call in `gulpfile` to fit new Node API
* Upgrade to latest beta of `karma-webpack` and remove all code splitting in test
* Adapt preview script loader to work with new chunk optimization. This was the hardest part.
* Upgrade `offline-plugin` and update configurations to work with latest version
=> Upgrade to Webpack 4

package.json, yarn.lock
Upgrades all semver dependencies that don’t have major complications (e.g. stylelint, where we muck with the internals)
=> Simple semver dependency upgrades

webpack.config.js
Optional caches require the assets be hashed and available permanently, which is the case in production.
=> Mark production as safe to use optional caches

webpack.config.js
Automatically generates `<link rel="prefetch">` resource hints for async JavaScript chunks. Inspired by the recent updates to Webpack supporting this as built-in functionality, but actually uses the `script-ext-html-webpack-plugin`, which uses the native browser feature rather than reimplementing it in JavaScript. The native functionality should be more efficient since the browser can start doing work before the main JS is loaded.
Unfortunately this does mean that Safari won’t benefit from the prefetching at all, since it doesn’t support prefetch resource hints, but it’s just a performance optimization so not the end of the world.
=> Prefetch async chunks

src/components/Output.jsx, src/components/Workspace.jsx, src/containers/Output.js, src/containers/Workspace.js, src/selectors/index.js, src/selectors/isDraggingColumnDivider.js
This PR containerizes the Output.
@outoftime I think the draggable console PR was getting a bit unruly. I thought it would be better to chunk it out into some separate PRs. Doesn't do much as a stand alone but should make it easier to implement the console divider drag later on.
=> containerize output

src/clients/firebase.js
The next user that imports it won't be able to export to repo since they don't
own it.
I look forward to the discussion as to whether this should be a whitelist or blacklist
=> Remove externalLocations from the project before exporting to snapshot

src/components/ConsoleInput.jsx, src/components/Editor.jsx, src/components/PreviewFrame.jsx, src/components/Workspace.jsx, yarn.lock
Upgrades `react` and `react-dom` from 16.3 to 16.4. Also upgrades `eslint-plugin-react` to 7.8.2.
The React changelog does not list anything relevant, but according to the latest `eslint-plugin-react`, the `componentWillReceiveProps` and `componentWillMount` lifecycle methods have been deprecated since React 16.3. I don’t think this is actually correct—the React team has simply indicated that they will be deprecated in the future—but since the linter was failing on the presence of those methods, no time like the present. So, migrated the components that used the to-be-deprecated lifecycle methods to use non-deprecated ones.
https://github.com/facebook/react/blob/master/CHANGELOG.md#1640-may-23-2018
https://github.com/yannickcr/eslint-plugin-react/blob/master/CHANGELOG.md#780---2018-05-11 …
=> Upgrade React to 16.4

src/components/Instructions.jsx, src/components/TopBar/index.jsx
Moving the bootstrap action to `componentDidUpdate()` in `<Workspace>` did end up causing a brief moment where certain props are not present.  Did not break anything, but does cause prop type validations. So, mark them as not required and add defaults.
=> Add default props where needed

docker-compose.yml
There’s not much reason to have node_modules in a volume unless you’re trying to run Popcode both in a Docker container and on the host (in which case natively compiled modules could cause a problem). So, just share `node_modules` between the container and host machine. In particular this allows us to straightforwardly use `eslint` and friends in editor integrations.
=> Share node_modules between Docker and host

package.json, yarn.lock
Upgrades to 2.0.0, for compatibility with the Remark version we’re already using.
=> Upgrade remark-external-links

src/clients/github.js
Missed a spot when moving the user profile information  to nested under `account`. Fixes gist/repo export, etc.
=> Fix GitHub client access token lookup

src/actions/ui.js, src/components/Console.jsx, src/components/ConsoleInput.jsx, src/components/Editor.jsx, src/components/EditorsColumn.jsx, src/components/NotificationList.jsx, src/components/notifications/GenericNotification.jsx, src/components/notifications/GistImportError.jsx, src/components/notifications/ProjectExportNotification.jsx, src/components/notifications/SnapshotNotification.jsx, src/records/EditorLocation.js, src/records/Notification.js, src/records/UiState.js, src/records/index.js, src/reducers/ui.js, src/selectors/getNotifications.js, src/selectors/getOpenTopBarMenu.js, src/selectors/getRequestedFocusedLine.js, src/selectors/isDraggingColumnDivider.js, src/selectors/isEditingInstructions.js, src/selectors/isExperimental.js, src/selectors/isTextSizeLarge.js, src/selectors/isUserTyping.js, test/unit/reducers/ui.js
Introduces three new `Record` types:
* `UiState`, containing top-level UI state
* `Notification`, which is what it sounds like
* `EditorLocation`, which identifies a specific line/column in a particular editor in the UI
Both `UiState` and `Notification` have simplified schemata from their previous `Map` representations:
* `UiState` is now flattened; the nesting didn’t really add clarity
* `Notification` no longer has a `payload` property; this has been merged into the existing `metadata` property
=> Use Immutable records for UI state

src/clients/github.js, src/sagas/clients.js, src/sagas/projects.js, test/helpers/Scenario.js, test/unit/sagas/clients.js, test/unit/sagas/projects.js
Passing the entire user unnecessarily couples the GitHub client to the data structure we use to store the logged in user information. Changing it to just take the access token enables a new use case during account migrate/merge, but I’m extracting this out into a separate pull request to make the incremental change.
=> Pass access token directly to GitHub client rather than entire user

locales/en/translation.json, src/components/TopBar/HamburgerMenu.jsx, src/components/TopBar/index.jsx
Takes primary google auth out of experimental mode and adds a login to GitHub button to the hamburger menu. @outoftime
=> switch primary login to google and add login with github button

src/components/InstructionsEditor.jsx, src/css/application.css
Resolves #1395 
New buttons:
These:
- Match top bar button stying
- Have a clear primary and secondary action
- Have equal widths (cancel was larger than save before)
=> Improved instructions editing buttons

src/components/TopBar/HamburgerMenu.jsx
Proximate motivation is fixing a missing `key` prop for the GitHub login item, but ultimately using an array in this situation (where there is actually a specific set of items we want to return) is no longer the preferred approach. Instead, use a `<Fragment>`.
=> Use a fragment rather than an array for hamburger menu items

locales/en/translation.json, src/actions/index.js, src/actions/user.js, src/clients/firebase.js, src/clients/github.js, src/components/AccountMigration.jsx, src/components/AccountMigrationComplete.jsx, src/components/AccountMigrationError.jsx, src/components/AccountMigrationInProgress.jsx, src/components/AccountMigrationUndoGracePeriod.jsx, src/components/Modal.jsx, src/components/ProposedAccountMigration.jsx, src/components/Workspace.jsx, src/containers/AccountMigration.js, src/css/application.css, src/enums/index.js, src/html/index.html, src/records/AccountMigration.js, src/records/User.js, src/records/index.js, src/reducers/projects.js, src/reducers/user.js, src/sagas/user.js, src/selectors/getCurrentAccountMigration.js, src/selectors/index.js, test/unit/reducers/projects.js, test/unit/reducers/user.js, test/unit/sagas/user.js
Sets up a process for migrating an old GitHub-based account into a new Google-based account, merging the data and credentials for the two accounts.
The process is initiated by attempting to link GitHub. If the GitHub account you try to link is already associated with another Firebase account, you’re prompted to merge them:
If you choose to proceed, there is a five second grace period during which you can cancel the operation, before anything happens (in case you clicked yes by mistake):
After five seconds have passed, the process begins:
Once it’s done, you get a success message:
Info-level notices are sent to Bugsnag when a migration attempt begins, and when it completes successfully. If there is an error during migration, it is handled by the saga, reported to Bugsnag, and an error …
=> Account migrate/merge (experimental only)

src/createApplicationStore.js
Realized we have a huge hole in our error monitoring—uncaught errors that happen inside `redux-saga` call paths are caught by `redux-saga` itself, meaning they’re not captured as uncaught exceptions or unhandled promise rejections. So, we need to explicitly send them to Bugsnag.  Fortunately, `redux-saga` does provide an `onError` callback when creating the middleware that actually runs sagas, which is intended for just this use case. Add that callback and report errors to Bugsnag.
=> Report uncaught errors in sagas to Bugsnag

src/sagas/user.js, test/unit/sagas/user.js
When we get an `auth/credential-already-in-use` with no credential, send both a cloned copy of the error and the result of calling `error.toJSON()`, which for some reason returns an object with a different shape.
=> Send detailed information about error missing credential

package.json, yarn.lock
Upgrades Firebase packages from SDK version 5.0.4 to latest 5.3.1.
This is a shot-in-the-dark attempt to fix a bug where `auth/credential-already-in-use` errors do not include a credential in the payload, even though they are always supposed to.
Reviewing the changelog, there do not appear to be any breaking changes.
=> Upgrade Firebase to latest

src/clients/firebase.js, src/sagas/user.js
Because of what I believe is a bug in the Firebase SDK, we don’t get a credential back with the auth error unless the response from GitHub includes an email address. I will file a bug with the SDK, but in the meantime, requesting `read:user` and `user:email` is a viable workaround.
Also removes the detailed error logging since I found the root cause of the error.
=> Add email and profile scopes to GitHub

.gitignore, docker-compose.yml
Adds `docker-compose.override.yml` to `.gitignore` so that people can easily override local `docker-compose` configurations to their liking. I used this to set up NFS mount of the project directory. Also removes the explicit bind mount for `node_modules`, which was a very minor optimization but makes overriding the mount much more annoying.
=> Local override for Docker configuration

locales/en/translation.json, src/actions/clients.js, src/actions/index.js, src/reducers/ui.js, src/sagas/clients.js
If we fail to load `gapi`, for instance if there is no internet connection, Popcode should still be basically usable. Previously this situation would throw a promise rejection which was not handled, thus breaking out of the saga loop and causing the app to stop functioning properly. Now we handle the rejection and display a message to the user explaining the situation.
=> Handle gapi load failure

src/components/Workspace.jsx, src/containers/Workspace.js, src/css/application.css
=> Add subtle edit button to instructions bar

package.json, src/components/EditorsColumn.jsx, src/components/Workspace.jsx, src/css/application.css, src/higherOrderComponents/resizableFlex/index.js, src/higherOrderComponents/resizableFlex/isFlexResizingSupported.js, src/higherOrderComponents/resizableFlex/sham.js, webpack.config.js, yarn.lock
Was testing for regressions after upgrading a library and realized that old browsers are totally broken. Had to do several fixes for Chrome 23 and one more for Safari 7.1:
* Remove the `<main>` tag (React requires that all tags used in JSX are recognized by the browser; old Chrome does not know about the `<main>` tag)
* Polyfill `requestAnimationFrame`
* Only do flex resizing on browsers that implement the modern flexbox standard; sham out the functionality on older browsers
* Clone the `style` object received as a prop by `EditorsContainer`
=> Fixes for older browsers

README.md, gulpfile.js, package.json, yarn.lock
Switches from postcss-cssnext to postcss-preset-env, which is now the
recommended plugin. Confirmed that this still works fine on super-old browsers.
Proximate motivation was getting a yarn upgrade to work, weirdly.
=> postcss-preset-env

.travis.yml, Dockerfile, gulpfile.js, package-lock.json, package.json, webpack.config.js
Run the build in Docker on Travis. This has a few advantages:
* Removes duplication—`Dockerfile` becomes the source of truth for Travis, as well as for development for those who use Docker in development
* Makes CI more portable
* Should in principle make builds faster, as we can push release images to Dockerhub, and then use the image layers as a cache for the next build. This will allow new builds to, at a minimum, reuse the OS-level dependency installations, and for branches that don’t change the node modules, reuse the NPM installation as well. However we need to merge this and get an initial image pushed to Dockerhub before I can add configuration to the build to use the Dockerhub image for caching
=> Travis uses Docker

.travis.yml, Dockerfile
* Use `npm ci` rather than `npm install`
* Point Docker build at latest release image on Dockerhub to use as cache layer
* Add missing image name in run command for `syncFirebase`
=> Docker build improvements

.travis.yml, README.md
`--cache-from` won’t pull the image for you.
Also mention doing this in the README.
=> Explicitly pull latest release Docker image

.travis.yml, Dockerfile
Prefixing a command with `npx` will effectively add your local `node_modules/.bin` to the `$PATH` for the purposes of running that command. Unlike `npm run`, though, it will still run an executable that lives in another location on your `$PATH`. So, prefixing all commands run in the Docker container with `npx` should be harmless, and reduces boilerplate in the Travis build configuration.
=> Use npx as entrypoint for docker container

Dockerfile
It’s generally good practice to combine multiple `RUN` commands that form a single logical operation into a single `RUN` command with multiple shell statements therein. This avoids creating unnecessary intermediate build layers, thus making build caching more efficient.
Specifically we combine:
* Steps to add Google’s apt signing key, add Google’s apt repository, update all dependencies, and install Chrome
* Steps to configure Bower and NPM respectively to run as root
=> Consolidate build steps

package-lock.json, package.json
* `firebase-app`: `0.3.3` -> `0.3.4`
* `firebase-auth`: `0.7.2` -> `0.7.6`
* `firebase-database`: `0.3.4` -> `0.3.6`
Overall SDK version upgrade from 5.4.0 to 5.5.1
Nothing in the changelog appears to affect us.
=> Upgrade Firebase packages

src/reducers/ui.js, test/unit/reducers/ui.js
Deletes notification from Redux store in the `UPDATE_PROJECT_SOURCE` reducer.
Fixes #1048
=> Dismiss Snapshot Notification after Project is Updated

src/css/application.css
In our class, with spotty internet, Popcode loaded but the google font did not. Since the font defaulted to the built-in browser serif font, it looked strange and visually the cursor was greatly offset from where it actually was. This adds the default monospace font as a fallback, which might not work perfectly, but should work much better.
=> Add monospace font fallback

src/css/application.css
Set padding for inline code in headers without affecting the padding of code blocks. This passes testing (although it's necessary to specify `postcss-bem-linter: ignore` on line 321 in order to do so).
Addresses [#1346](https://github.com/popcodeorg/popcode/issues/1346)
=> Set padding for inline code in headers

.docker-sync-env, docker-compose.sync.yml
`docker-sync` allows much faster shared filesystem access than the standard osx bind mount, by using a named mount in the Docker container and then separately syncing that volume with a bind mount to the host. It’s optional, but for those craving faster file access while also having the `node_modules` directory visible on the host machine, it’s very good.
=> Set up docker-sync

src/channels/makeLoginState.js, src/clients/firebase.js, src/services/gapi.js
Two fixes, not directly related but both in the same code path.
First, in the case where we need to instruct `gapi` to open a popup, we have to do so in the context of a synchronous user action handler. So, we can’t use the usual approach of awaiting the promise of loading and configuring `gapi` and then calling the popup on the resolved value. For that case, we expose `getGapiSync()`, which returns `gapi` if it’s loaded and throws an error if it isn’t. The idea is that callers to `getGapiSync()` are responsible for ensuring that `gapi` is definitely loaded before calling the method.
However, `signOut()` can be called very early in the application lifecycle, specifically if there is a Firebase session that no longer has a corresponding short-lived session cookie. Further, we don’t need to …
=> Fix initial login errors

src/records/UserAccount.js, src/records/UserIdentityProvider.js, src/records/index.js, src/reducers/user.js, src/sagas/clients.js, src/sagas/manageUserState.js, src/selectors/makeIsUserAuthenticatedWith.js, test/helpers/Scenario.js, test/helpers/factory.js, test/unit/reducers/user.js, test/unit/sagas/clients.js
Creates a UserIdentityProvider record, which contains information about a linked user identity (Google, GitHub, etc). Currently this just stores a single property, which is an `accessToken`. Replaces the previous approach of storing access tokens as in a map with string values. The `identityProviders` collection is still a map, with the keys as the `providerId` (`"github.com"`, `"google.com"`, etc.)
This doesn’t get us anything immediately, but is a prerequisite to two needed changes:
1. Detect situations where the user has linked an identity provider (information that’s available in their Firebase user account object when they log in), but we don’t have a stored credential for that identity (e.g. a network error prevented us from saving the GitHub credential after they linked their …
=> Store linked identity information in objects

package-lock.json, package.json
I was running into this issue with the tests locally, and was able to verify using `nvm` that it was solely caused by the version of this dependency:
https://github.com/karma-runner/karma-browserstack-launcher/issues/140
=> Update karma-browserstack-launcher to be compatible with node 10+

src/services/gapi.js
Because they changed it without warning and broke the old one.
Fixes #1628
=> Update Google Classroom API discovery docs URL

Dockerfile, package-lock.json, script/package-strict, src/clients/firebase.js, src/clients/github.js, src/components/PreviewFrame.jsx, src/sagas/errors.js, src/util/compileProject.js
Upgrades npm to latest 6.7.0 (and Node to latest 8.X while we’re      in there), then regenerate `package-lock.json` by temporarily      locking all first-order dependencies to exact versions, deleting      `package-lock.json` and the contents of node-modules, and then running an `npm install`.
Various people have had issues with `package-lock` containing a      ton of unrelated changes after installing new dependencies; the      previous `package-lock` if I’m not mistaken was derived from one      converted from the `yarn.lock` file we used with Yarn. Hopefully      a freshly-generated one should behave better.
=> Regenerate package-lock.json from scratch with latest npm

.projections.json, package.json, test/unit/Analyzer.js, test/unit/higherOrderComponents/resizableFlex/calculateFlexGrowAfterDrag.js, test/unit/localization/localization.js, test/unit/reducers/clients.js, test/unit/reducers/console.js, test/unit/reducers/currentProject.js, test/unit/reducers/errors.js, test/unit/reducers/projects.js, test/unit/reducers/resizableFlex.js, test/unit/reducers/ui.js, test/unit/reducers/user.js, test/unit/sagas/clients.js, test/unit/sagas/compiledProjects.js, test/unit/sagas/errors.js, test/unit/sagas/manageUserState.js, test/unit/sagas/projects.js, test/unit/sagas/ui.js, test/unit/sagas/user.js, test/unit/util/javascript.js, test/unit/util/queryParams.js, test/unit/validations/css.js, test/unit/validations/html.js, test/unit/validations/html/rules.js, test/unit/validations/html/runRules.js, test/unit/validations/javascript.js, yarn.lock
I’d like to move away from tape entirely, but at least it would be nice for errors thrown from tests to be reported as test failures, rather than crashing the entire process.
=> Use tape-catch instead of regular tape

package.json, test/unit/validations/css.js, yarn.lock
So before merging... I seem to have noticed that the acceptance testing is not actually testing anything.
I manually updated `acceptance.json` because `update-validation-acceptance` script wasn't working for me and intentionally tried to get it to fail by running `yarn test` by not including the library update.
@outoftime Any thoughts? Does this have to do with the most recent yarn change?
=> #1461 Updated PrettyCSS library and acceptance testing

.eslintrc, bower.json, package.json, src/config/libraryAssets.js, webpack.config.js, yarn.lock
This one was straightforward - jQuery's npm package ships with a dist
version that can be easily dropped in where the bower one was before.
The first of many steps for #1442
=> Source jQuery from npm, not bower

src/reducers/user.js, src/sagas/manageUserState.js, test/unit/sagas/manageUserState.js
For reasons that are as yet unclear, some users have GitHub credentials but don’t actually have a GitHub account linked. Currently this causes an error when logging in, and the error is thrown before the user has successfully authenticated, meaning the error report has no user information.
For now we simply ignore credentials that don’t have a corresponding entry in `providerData`, and send a warning report to Bugsnag. This should allow me to accumulate enough data to figure out the problem.
Fixes #1647
=> Report to Bugsnag if user providers don't match credential providers

.eslintrc, package.json, webpack.config.js
We want the build to fail if any linter rules are violated; the most obvious (and in the past, only) way to do this is to make all rules errors.  However, that is obnoxious when looking at output from eslint-webpack-plugin and using editor integrations; warnings should be displayed as warnings. We can now have and eat cake by making most rules `warn` instead of `error`, and passing the option `--max-warnings=0` to eslint so that the process still exits with a non-zero code if there is a warning.
=> Make most eslint errors warn

.travis.yml, package.json, script/check-duplicate-dependencies, yarn.lock
Left to its own devices, `yarn` will often install multiple versions of the same package, even when a single version will satisfy all (or a larger subset of) dependencies. The [`yarn-deduplicate`](https://www.npmjs.com/package/yarn-deduplicate) package fixes this by manually updating `yarn.lock` to install the fewest dependencies.
This ends up having little practical effect on bundle size, but does fix something that annoys me almost every time I install or upgrade a dependency.
This pull request:
* Makes `yarn-deduplicate` a development dependency
* Deduplicates the current `yarn.lock` file
* Adds a `yarn deduplicate` command to the `package.json` scripts that runs it with the appropriate flags
* Adds a `script/check-duplicate-dependencies` which will fail if `yarn.lock` is not fully …
=> Use yarn-deduplicate to resolve duplicate package dependencies

package.json, src/util/bugsnag.js, yarn.lock
Replaces `bugsnag-js` and `bugsnag-react` with `@bugsnag/js` and
`@bugsnag/plugin-react`. Updates our client module to use these and
accommodate slight changes in the API for setting up the React plugin.
=> Upgrade to latest Bugsnag client packages

package.json, test/helpers/i18nFactory.js, yarn.lock
11.9.0 &rarr; 15.0.6
Had to update a call to `init()` in the test helper to not expect `init()` to return the instance.
Otherwise, nothing particularly interesting in the [changelog](https://github.com/i18next/i18next/blob/master/CHANGELOG.md).
=> Upgrade i18next to latest

locales/en/translation.json, package.json, src/components/Application.jsx, src/components/BrowserError.jsx, src/components/PreviewFrame.jsx, src/services/bowser.js, src/util/normalizeError.js, yarn.lock
Upgrades from 1.9.4 &rarr; 2.1.2. Major breaking API change, now export a singleton parser from the `bowser` service.
=> Upgrade bowser

locales/en/translation.json, src/components/CollapsedComponent.jsx, src/components/Console.jsx, src/components/EditorsColumn.jsx, src/css/application.css
This is the some groundwork for allowing the preview to be minimized.
`CollapsedComponent` unifies the collapsed UI for the currently
collapsible components (the 3 editors and the console).
There shouldn't be user-facing changes here.
Starts to fix: #1340
=> Introduce `CollapsedComponent` for minified component

bower.json, package.json, src/config/libraryAssets.js, webpack.config.js, yarn.lock
Take an upgrade to the latest version while we're at it.
Relates to: #1442
=> Source p5 from npm instead of bower

bower.json
We're in the process of migrating away from bower so we can start by
removing the stuff it installs that we aren't using.
=> Clean up unused bower dependencies

src/components/Preview.jsx, src/components/Workspace.jsx, src/containers/Preview.js, src/containers/Workspace.js, src/css/application.css, src/selectors/getCurrentProjectPreviewTitle.js, src/selectors/index.js, src/util/ui.js
Finishes the work around this feature.
- Make the `Preview` Component collapsible
- When `Preview` and `Console` are both collapsed, hide the whole right column
- Handle the case where everything is collapsed separately for clarity - I chose to handle it as a separate case as opposed to just picking the right or left column and throwing everything in there - in this case both the left and right column are not rendered and a third, different column is instead.
- Handle various edge cases regarding validation and errors while the preview is collapsed - general heuristic was if there are errors to show we show the right column even if everything is collapsed.
There are a few inconsistencies between how runtime errors and static analysis errors are handled, namely the static errors take over …
=> Make `Preview` component collapsible and handle completely collapsed right column

tools/setup
=> Fix reversed logic of OSX checks

babel.config.js, config/browsers.json, webpack.config.js
This reimplements https://github.com/popcodeorg/popcode/pull/1674, which was previously reverted because it fails on Chrome 38. With this change, one option was to preventing the `@babel/plugin-transform-typeof-symbol` module from being run through the build, because that transform causes issues in chrome 38. The other option was to find already-ES5 modules that don't need to be recompiled, and `brace` fixes the issue.
=> Run all node_modules through babel

locales/en/translation.json, src/components/TopBar/CurrentUserMenu.jsx, src/css/application.css
This addresses issue #1644 using @pwjablonski previous models. This PR adds fontawesome icons to the current user menu items. It adds a Github icon to the "link Github" menu item, an unlink icon to the "unlink <user>'s Github" menu item, and a logout icon to the "logout" menu item. It also changes the text from "unlink Github account for <user full name>" to "unlink <user first name>'s Github". Creates two new css classes to style icons and text within each menu item.
=> Updates CurrentUserMenu with icons

Dockerfile, package.json
Upgrades Node in the build environment to 10.16.0, the current LTS version. Also upgrades Yarn to 1.17.3, the latest.
=> Upgrade Node and Yarn

locales/en/translation.json, src/components/TopBar/CurrentUserMenu.jsx, src/css/application.css
Reverts popcodeorg/popcode#1712
The call to `split` causes an error when the display name is null; this is happening enough that we should fix and then re-release this.
=> Revert "Updates CurrentUserMenu with icons"

locales/en/translation.json, src/components/TopBar/CurrentUserMenu.jsx, src/css/application.css
Adds icons from fontAwesome to CurrentUserMenu items (link Github account, unlink Github account , and logout). Fixes bug for when user displayName is null. Changes top-bar-unlink-github text translation and adds a top-bar-unlink-github-default text translation.
=> Link unlink icons fix

.eslintrc, src/services/babel-browser.gen.js, webpack.config.js
In cases where we are inspecting paths from the filesystem, we should be agnostic to path separator, instead using the built-in functions available in the `path` module.
I don’t think this is necessary when _writing_ paths, as I believe Node normalizes paths using `/` on Windows.
=> Platform-agnostic path separators

config/lintignore, tools/setup.py
* Add `/dist` to linter ignore
* Check for existence of `.git/info/exclude` before trying to write to it
* Add newline after entry in `.git/info/exclude`
Fixes #1735
=> Development environment fixes

contrib/vscode/tasks.json
Feels better to have task names look similar to VS Code commands.
=> Update task names to reflect conventions of VS Code command names

contrib/vscode/tasks.json
* Call `yarn preview`, not `yarn static`
* Also add bundle profiling since this is a common use case
=> Update static server task

tools/node.py, tools/npx.py, tools/setup.py, tools/util/__init__.py, tools/yarn.py
Running a `tools/` command should implicitly guarantee that the environment is correctly set up. To support this:
* Streamline `tools/setup.py` for the no-op case, in particular cheaply checking if the correct version of `yarn` is installed before installing it
* Add calls to `setup()` from relevant `tools/` scripts; in some cases, we skip installing node module dependencies via yarn (e.g. if you invoke `yarn.py` with an installation-related command)
=> Ensure environment is up to date from all tools commands

.renovaterc.json
For dependencies that are only used when linting/testing, a green build is by definition sufficient to ensure that they did not break anything. So, automerge those dependencies.
Also adds a group for `lodash` and the individual `lodash.*` packages used in build scripts, so they stay in sync.
=> Automerge test-only dependencies

package.json, src/components/TopBar/createMenu.jsx, yarn.lock
Upgrading `react-onclickoutside` to the latest version broke its behavior for reasons I wasn’t able to fully unravel, but ultimately I have always found its approach a little clunky. Switch to [`use-onclickoutside`](https://github.com/Andarist/use-onclickoutside), which just exposes a nice little hook that takes a `ref`. And it works!
=> Switch from react-onclickoutside to use-onclickoutside

.yarnrc, contrib/vscode/extensions.json, contrib/vscode/settings.json, package.json, yarn.lock
* Fixes `.yarnrc` syntax so that we are, in fact, pinning versions on install
* Adds `vscode-yarn` to recommended extensions and configures it to use `tools/yarn.py`
* Pins the version of recently-installed `use-onclickoutside`
=> Yarn-related improvements

locales/en/translation.json, src/validations/__tests__/html.test.js, src/validations/html/htmllint.js
Reverts popcodeorg/popcode#1856
Rolling back because #1894 looks fairly bad—the validation loop permanently crashes when the validator sees an unfinished `<a  href`, which is bound to be very likely in the normal course of typing HTML.
=> Revert "Allow tel: and mailto: patterns in href attributes"

package.json, src/components/TopBar/createMenu.jsx, yarn.lock
Fixes the order of hooks in `createMenu`; also adds `eslint-plugin-react-hooks` to catch any future problems along these lines.
=> Fix hook order in createMenu

.eslintrc.json
In #1896 I added `eslint-plugin-react-hooks` to dependencies but forgot to actually add it to the config or enable any rules.
=> Actually use react-hooks linter

Dockerfile, package.json
Upgrades build/test runtime to Node 12, which is now in LTS. Also bump yarn to the latest patchlevel while we’re in there.
=> Upgrade Node to 12

.eslintrc.json, package.json, src/clients/firebase.js, src/components/ConsoleInput.jsx, src/components/Editor.jsx, src/components/ErrorReport.jsx, src/containers/AssignmentCreatorForm.js, src/createApplicationStore.js, src/higherOrderComponents/resizableFlex/index.js, src/higherOrderComponents/resizableFlex/sham.js, src/init/DOMParserShim.js, src/reducers/projects.js, src/sagas/compiledProjects.js, src/sagas/projects.js, src/selectors/getCurrentCompiledProjectKey.js, src/selectors/getCurrentProjectPreviewTitle.js, src/selectors/getHiddenUIComponents.js, src/util/performWithRetries.js, src/validations/__tests__/validationHelper.js, src/validations/html/rules/MismatchedTag.js, src/validations/html/rules/NodeOutsideBody.js, test/unit/sagas/ui.js, yarn.lock
Adds eslint-plugin-lodash, and enables a modified version of the recommended configuration. In particular, most rules are downgraded to warnings; and the `prefer-lodash-method` rule is turned off (it’s a bit aggressive, though I like it from a “one right way to do things” perspective). Also, the path style is set to `array`, as this is meaningfully faster per https://jsperf.com/lodash-get-string-vs-array
=> Add eslint-plugin-lodash

.renovaterc.json
Sweetalert2 is constantly releasing new versions, and the changes are never relevant to us—manually reduce its priority in Renovate so that it does not get in the way of other things.
Also add `caniuse-lite` to the automatic upgrade list.
=> Make sweetalert2 last priority for upgrades

contrib/vscode/extensions.json, contrib/vscode/settings.json
The old canonical VS Code stylelint extension was pulled because it is unmaintained. There are several forks but this one looks like it will probably become the new canonical: https://github.com/ilokoodi/vscode-stylelint
So, switched recommended extensions to this but it’s disabled in the config for now, because the extension ships with an outdated version of stylelint which does not recognize some newer rules that are enabled with presets we use. Per https://github.com/ilokoodi/vscode-stylelint/issues/4 this is being actively worked on; I will monitor that issue and reenable the extension once a fixed version is shipped.
=> Switch to maintained Stylelint extension

.renovaterc.json
Can’t remember a time when a minor version upgrade caused a breaking change that wasn’t caught in tests, so let’s have faith in semver.
To somewhat reduce the risk factor here, only perform dependency upgrades on weekends—makes it much more likely that any problem that slips through will be caught by instructors during lesson prep rather than in the classroom.
=> Automerge all dependency upgrades except major

package.json, src/logic/__tests__/helpers.js, src/logic/__tests__/linkGithubIdentity.test.js, src/logic/__tests__/logout.test.js, src/logic/__tests__/startAccountMigration.test.js, src/logic/__tests__/unlinkGithubIdentity.test.js, src/logic/startAccountMigration.js, yarn.lock
Instead of exercising logics by calling the `process()` method directly, creates a `makeTestLogic` test helper that sets up a mock store with the `redux-logic` middleware configured with only the logic under test.
This change was initially motivated by an observation that several of our logic tests were relying on the implementation detail that our `process()` methods tend to be async methods that settle when the logic is done; however, in those cases, what actually matters is the `done()` callback being called.
After a first cut that created a test helper that replicated the way `redux-logic` handles different implementations of the `process()` method, I still didn’t like how much manual testing of Observables and such we had to do for the more advanced logics.
So, instead, test logics …
=> Test logics by running them through middleware in mock store

contrib/vscode/extensions.json, contrib/vscode/settings.json
As of https://github.com/stylelint/vscode-stylelint/issues/4 , the new(?) official VS Code stylelint extension bundles the latest version of stylelint and supports auto-fixing. So, point to that as the recommended extension, and reenable stylelint validation in the VS Code development environment.
=> Use official VS Code Stylelint extension

contrib/vscode/settings.json, yarn.lock
Upgrades all indirect dependencies by deleting `yarn.lock` and then running `yarn install`. This is safe since our `package.json` pins all direct dependencies to exact versions.
Proximate motivation is that `fsevents` 1.x is an indirect dependency via several direct ones; we were resolving this to 1.2.7, which does not build properly on Node 12. Re-resolving dependencies bumps it up to 1.2.11, which works properly. This fixes an issue with high CPU usage from the development server on OS X development environments.
Also sets the Yarn VS Code extension to show its output under Output, not in a terminal window, like every other extension.
=> Upgrade indirect dependencies

contrib/vscode/tasks.json
Adds a VS Code task to pull from `upstream/master` with interactive rebase. This is a common enough workflow and it’s not supported by VS Code’s built-in git integration.
=> Add task for pull with interactive rebase

__mocks__/mixpanel-browser.js, package.json, src/actions/instrumentation.js, src/application.js, src/clients/mixpanel.js, src/components/AceEditor.jsx, src/components/CodeMirrorEditor.jsx, src/components/EditorsColumn.jsx, src/components/__tests__/CodeMirrorEditor.test.jsx, src/config.js, src/containers/EditorsColumn.js, src/logic/__tests__/instrumentApplicationLoaded.test.js, src/logic/__tests__/instrumentEnvironmentReady.test.js, src/logic/index.js, src/logic/instrumentApplicationLoaded.js, src/logic/instrumentEnvironmentReady.js, webpack.config.js, yarn.lock
Sets up Mixpanel to track load performance. In particular, we are tracking an `Environment Ready` event, which corresponds to at least one editor instance being fully initialized.
Also adds an `Experimental Mode` property to all Mixpanel events, so that we can break down observations along that dimension if we are so inclined.
=> Use Mixpanel to track load performance

__mocks__/firebase/app.js, __mocks__/i18next.js, __mocks__/offline-plugin/runtime.js, src/application.js, src/components/Application.jsx, src/components/Workspace.jsx, src/containers/Workspace.js, src/init/__tests__/index.test.js, src/init/index.js, src/init/initI18n.js, test/index.js
App initialization logic has historically occurred in two places:
* In top-level code in the `application` module
* In the mount hook for the `<Workspace>` component
The former is hard to test and not necessarily intuitive; the second is out-of-place since none of the initialization logic is in fact related to the component in question.
So, consolidate all initialization logic into a new index module for the `init` package; a single `init()` function is now the single entrypoint into initialization. As well as better organization this also made it more practical to write tests for application initialization.
=> Consolidate app initialization logic

yarn.lock
Upgrades all indirect dependencies to latest versions, by deleting and regenerating `yarn.lock`.
=> Bump indirect dependencies

Dockerfile, package.json, yarn.lock
* Upgrade yarn to 1.21.1
* Removes a handful of extraneous dependencies from `yarn.lock` by running `yarn install --check-files`
=> Upgrade yarn to 1.21.1

package.json, src/validations/Validator.js, src/validations/html/rules/Code.js, yarn.lock
Our preferred enum library is [enum](https://www.npmjs.com/package/enum), but [enumify](https://www.npmjs.com/package/enumify) snuck in there when I wasn’t paying attention. It’s got a goofy interface, which got goofier with the latest major version release. Just replace its one use in the codebase with enum.
=> Remove enumify from dependencies

src/validations/__tests__/javascript.test.js, src/validations/javascript/jshint.js
This fix will show a helpful error message for multiple declarations using ES6 syntax (let/const). Doesn't do anything for multiple var declarations with the same name.
This is my first PR to Popcode, should I add tests? If so could you tell me where I should be looking for tests in a similar vein? Thanks!
=> fix: handle duplicate js variable declaration

package.json, yarn.lock
Upgrades all transitive dependencies to latest by deleting and regenerating `yarn.lock`. This is safe for direct dependencies because all versions are pinned in `package.json`.
Also fixes duplicate entry for `highlight.js` in `package.json` while we’re in there.
=> Upgrade all transitive dependencies to latest

package.json, yarn.lock
Upgrades `inline-style-prefixer` to latest version, which fixes incompatibility with newer `browserslist` versions. Accordingly, also remove the yarn `resolutions` override for `browserslist`.
=> chore: Upgrade inline-style-prefixer

bower.json, gulpfile.js, package.json, yarn.lock
This also upgrades us from 4.1.1 -> 8.0.1. Diffing these two versions
makes it look like the changes are not trivial but a visual inspection
turns up no obvious visual regressions.
Partially Fixes: #1442
=> Source `normalize.css` from npm instead of bower

src/clients/firebase.js, src/components/Console.jsx, src/components/ConsoleInput.jsx, src/components/Editor.jsx, src/components/EditorsColumn.jsx, src/containers/Console.js, src/containers/EditorsColumn.js, src/init/__tests__/index.test.js, src/init/index.js, src/logic/instrumentApplicationLoaded.js, src/records/UiState.js, src/reducers/__tests__/ui.test.js, src/reducers/ui.js, src/selectors/getRemoteConfig.js, src/selectors/index.js, src/util/bugsnag.js, src/util/queryParams.js
Adds integration with [Firebase remote config](https://firebase.google.com/docs/remote-config), and uses remote config to gate the new CodeMirror editor implementation. This will allow us to do a gradual rollout of CodeMirror while closely monitoring for errors and bugs, with the ability to roll back the config change a bit more quickly than a full release would take.
This also includes a mechanism for overriding any remote config setting using a query parameter, which will afford a quick workaround if anyone runs into trouble with the new editor.
=> chore(editor): Gate CodeMirror editor with Firebase remote config

.renovaterc.json, package.json, yarn.lock
Downgrades `highlight.js` to 10.0, prior to the introduction of the `SHEBANG` utility which seems to have caused a regression.
Renovate is configured to only upgrade when a new version is released, and not to automerge when that happens.
Fixes #2336
=> fix(deps): Downgrade highlight.js

contrib/vscode/launch.json, tools/node.py, tools/npx.py, tools/setup.py, tools/teardown.py, tools/yarn.py
Running the setup script causes one of the node processes run by setup to capture the debugging session. Since it’s vanishingly unlikely that one would run the Jest debugger directly after pulling updates, we just skip the setup step when running the Jest process that needs to run the debugger.
Also applies Black formatting to all our Python setup scripts, sorry.
=> chore(tests): Skip environment setup when running Jest debugger

.renovaterc.json, package.json, yarn.lock
`eslint_d` is useful if you’re using a traditional editor like vim with linting integration, but it’s not needed for the supported Popcode development environment which is based on VS Code. Anyone who wants to use it can just install it globally.
=> chore(deps): Remove eslint_d

src/clients/github.js
The `github` client module hard-coded the assumption that the default branch’s name is `master`. This is no longer true; it is now `main`.
Fix the bug by hard-coding the assumption that the default branch’s name is `main`.
=> fix: GitHub default branch name is now main, not master

.renovaterc.json
Mostly removes a Renovate config group that bundled together all webpack-related packages even though many of them are third-party and even the ones under `webpack-contrib` are not released concurrently with webpack itself.
=> Unbundle webpack upgrades

.circleci/config.yml, .renovaterc.json
* Add backslashes
* Specify tag name explicitly
=> Fix deploy phase errors

.renovaterc.json
We rely on `script-ext-html-webpack-plugin` which doesn’t support Webpack 5 and [apparently never will](https://github.com/numical/script-ext-html-webpack-plugin#deprecation-warning). Webpack 4 is fine for now.
=> Don’t upgrade to Webpack 5
