popcodeorg/popcode

static/application.css
How this ever worked is a mystery to me.
=> Fix typo in CSS

src/components/output.jsx, src/components/workspace.jsx, src/config.js
Will be useful to have separate code paths; clearer what’s going on
=> Separate source state update from error state update

.projections.json
=> Projections

package.json, src/components/editor.jsx, src/components/errorList.jsx, src/components/output.jsx, src/components/workspace.jsx, src/config.js, src/services/storage.js
Using `localforage` as an abstraction for in-browser storage, ideally IndexedDB falling back to localStorage.
=> In-browser storage

package.json, src/components/errorList.jsx, src/components/toolbar.jsx, src/components/workspace.jsx, src/services/storage.js, static/locales/en/translation.json
* Create a new blank project
* Choose from a list of previous projects
=> Multiple projects

package.json
Also remove some unneeded dependencies
=> Move dev dependencies into correct category

.travis.yml
Not sure why that isn’t added by default
=> Add the skip_cleanup key

package.json, src/application.js, src/components/Editor.jsx, src/components/ErrorItem.jsx, src/components/ErrorList.jsx, src/components/ErrorSublist.jsx, src/components/LibraryPicker.jsx, src/components/LibraryPickerItem.jsx, src/components/Output.jsx, src/components/ProjectList.jsx, src/components/Toolbar.jsx, src/components/Workspace.jsx, src/validations/javascript.js
All components except `Workspace` are decoupled from Flux; `Workspace` handles propagating actions to Flux layer and constructing state from Flux.
In preparation for moving to Redux.
=> Decouple components from Flux

src/validations/css/prettycss.js
[PrettyCSS does not recognize `radial-gradient`](https://github.com/fidian/PrettyCSS/issues/38) and its vendor-prefixed equivalents, so just work around that by checking to see if the token for that error is a `radial-gradient` property and ignore the error if it is.
=> Ignore error messages caused by PrettyCSS not recognizing radial-gradient

.eslintrc, locales/en/translation.json, package.json, src/application.js, src/components/Toolbar.jsx, src/services/Gists.js, src/validations/css/prettycss.js
Allows user to export project as anonymous GitHub gist.
=> Basic Gist export

package.json, src/actions/__tests__/index-test.js, src/components/ErrorItem.jsx, src/components/ErrorSublist.jsx, src/components/LibraryPicker.jsx, src/components/Preview.jsx, src/components/Workspace.jsx, src/services/Storage.js, src/util/generatePreview.js, src/validations/css.js, src/validations/html.js, src/validations/html/htmllint.js, src/validations/html/slowparse.js
* Update to lodash 4
* Directly require modules for lodash functions that we need, rather than requiring entire library
=> Modular lodash

locales/en/translation.json, src/components/Editor.jsx, static/application.css
=> Language labels for editors

src/css/application.css
z-index is relative within the nearest z-indexed ancestor, so we can
just add z-index to a few containers to make things behave more
predictably.
=> Take advantage of relative z-index

README.md, package.json
=> Get some badges

locales/en.json, src/validations/javascript.js
Still a lot of errors in JSHint that we can handle, though—this is just covering a couple of common cases.
=> Improvements to JavaScript errors

src/components/Toolbar.jsx, src/config.js, src/css/application.css
=> Send feedback button

src/css/application.css, src/reducers/projects.js
Was being occluded by preview frame
=> Fix z-index in preview popout button

gulpfile.babel.js, npm-shrinkwrap.json, package.json, src/config.js, src/util/Bugsnag.js
=> Send app version to Bugsnag

locales/en.json, src/validations/javascript/esprima.js
E.g.:
```javascript
var name + 1;
```
=> Good error message when unexpected operator used

src/config.js
Right now it’s on in production! : 0
=> Fix check for LOG_REDUX_ACTIONS environment variable

package.json, src/components/Dashboard.jsx, src/components/Sidebar.jsx, src/components/Workspace.jsx, src/css/application.css
Sidebar is:
* Green if there are no errors
* Yellow if we’re currently validating
* Red if we have detected errors
=> Color of sidebar reacts to current error state

npm-shrinkwrap.json, package.json, spec/examples/validations/css.spec.js
Supports all flexbox properties:
* `align-content`
* `align-items`
* `align-self`
* `flex-direction`
* `flex-flow`
* `flex-wrap`
* `justify-content`
* `order`
=> Full support for Flexbox

locales/en.json, src/components/Dashboard.jsx, src/css/application.css
=> Bring back Send Feedback button

src/components/Dashboard.jsx
Also made all links open in a new tab while I was at it.
=> Add link to Slack signup in Dashboard

src/services/Gists.js, src/util/Bugsnag.js
Specifically motivated by the need to get to the bottom of a Gist export problem that a user is experiencing. In general, if we get an error from the API, we’ll send a report to Bugsnag that includes details of the failed request in the metadata.
Ideally, we’d also handle the error gracefully in the UI (show an error message, don’t open blank browser tab), but at this point I just want to get to the bottom of the underlying error in question.
This PR also adds a global handler for the `unhandledrejection` event, so we report unhandled promise rejections to Bugsnag; that does mean gist errors will double-report for now, but we definitely want to get reports for unhandled promise rejections.
=> Report details of errors interacting with GitHub API

spec/examples/actions/projects.spec.js
Not the most satisfying thing, but will have to do for now
=> Use a sinon timer to ensure that each project gets a unique timestamp

.travis.yml, npm-shrinkwrap.json, package.json
Checks to make sure `npm-shrinkwrap.json` is in sync with `package.json`
=> Run npm-shrinkwrap-check as part of build

src/components/Dashboard.jsx
=> updated slack link

src/services/Gists.js
When exporting a gist, any of the network requests may fail in unreliable network environments. So, in the event of a network error, we want to retry these operations several times:
* API request to create gist
* API request to update gist with URL
* API request to load gist by ID (for gist import)
I also took out the code that attempts an API request to load the gist after the export completes, because there is no evidence that this helps prevent a 404 when redirecting to the gist, and it’s another network request that can be slow or fail.
Fixes #331
=> Retry all network requests to GitHub

src/css/application.css
=> Set cursor: pointer for entire sidebar

src/css/application.css
Added `Inconsolata` font-family.
Rearranged properties in alphabetical order.
=> #558 Add Inconsolata font for label class selector

locales/en.json, npm-shrinkwrap.json, package.json, spec/examples/validations/html.spec.js, src/util/arrayToSentence.js, src/validations/html/htmlInspector.js
=> Special-case html validation for <li> without <ul>, <ol>, or <menu>

README.md
Links to reference documentation for the major tools and conventions used in the codebase.
=> Add a reference section to README

src/components/PopThrobber.jsx, src/css/application.css
Originally was contemplating a spinner but I changed it and forgot to change the CSS component name
=> Use pop-throbber as component name

README.md, package.json
=> Introduce an npm script for local development.

package.json, yarn.lock
So yarn stops whining about unmet peer deps
=> Add svgo to dependencies

.eslintrc, package.json, spec/assertions/validations.js, spec/examples/actions/ui.spec.js, spec/examples/validations/assertPassesAcceptance.js, spec/helpers/MockFirebase.js, spec/helpers/waitForAsync.js, src/actions/projects.js, src/actions/ui.js, src/components/ErrorSublist.jsx, src/components/Sidebar.jsx, src/components/Workspace.jsx, src/persistors/FirebasePersistor.js, src/reducers/runtimeErrors.js, src/reducers/ui.js, src/services/Gists.js, src/validations/Validator.js, src/validations/css.js, src/validations/css/css.js, src/validations/css/prettycss.js, src/validations/css/stylelint.js, src/validations/html.js, src/validations/html/htmlInspector.js, src/validations/html/htmllint.js, src/validations/html/slowparse.js, src/validations/importLinters.js, src/validations/javascript/esprima.js, src/validations/javascript/jshint.js
Paren-less is more idiomatic and less typing!
```js
collection.map(i => i % 2);
collection.map((i, j) => i * j);
collection.map((i) => {
if (i % 2 > 0) {
return 0;
}
return 1;
});
=> Don’t use parens for single arrow lambda parameter

src/util/generatePreview.js
https://github.com/popcodeorg/popcode/issues/698
=> Convert SweetAlert args to string

README.md, package.json
Add @razzius to contributors lists
=> Add Razzi to contributors

src/css/application.css
=> Make a distinct border between editors.

src/components/ErrorItem.jsx
=> Give contextual phrasing "On line x:" when presenting error messages

locales/en/translation.json, package.json, src/components/ErrorItem.jsx, src/components/PreviewFrame.jsx, src/config/previewFrameLibraries.js, src/util/generatePreview.js, webpack.config.js, yarn.lock
Reverts popcodeorg/popcode#726
Causes uncaught errors with malformed comments in the code. Need to properly protect against those.
=> Revert "Swap in loop-breaker for loop-protect"

README.md
=> add slack link to readme

gulpfile.js, src/css/application.css, static/index.html, webpack.config.js
=> relative paths

src/css/application.css, static/index.html
Heyo I'm interested in helping out with this project and thought I'd get my feet wet with one of the `good-for-beginner` issues! I chose https://github.com/popcodeorg/popcode/issues/368.
Gif showing the loader when refreshing the page: http://g.recordit.co/oVu9hYkZxd.gif
Screenshot of the loader (on a 13" screen):
I've attempted to follow conventions but please let me know if I can make this better in any way. Thanks!
=> Show a loading indicator while React is loading

package.json, yarn.lock
=> Upgrade babel-loader

.eslintrc, package.json, webpack.config.js, yarn.lock
Show lint errors in the dev server output
=> eslint-loader

yarn.lock
Upgrades all packages to the latest semver-compatible versions as
specified in `package.json`.
Will address major version upgrades in separate PRs.
=> Upgrade to latest semver-compatible versions

package.json, yarn.lock
Breaking changes [appear very minor](https://github.com/webpack/webpack/releases)—a sign of a good package. Application seems to work fine.
=> Webpack 3 upgrade

src/createApplicationStore.js
This should have been in https://github.com/popcodeorg/popcode/pull/905/files but it looks like it was never pushed.
=> Fix createLogger import

package.json, yarn.lock
Sourcemaps still seem to work fine
=> Upgrade gulp-sourcemaps

package.json, yarn.lock
[Very minor major version change](https://github.com/i18next/i18next/blob/master/CHANGELOG.md#800)
=> Upgrade i18next

package.json, yarn.lock
Should be the same actual code, just moving back to canonical package since it is now available on npm
=> Upgrade PrettyCSS

src/components/TopBar.jsx, src/containers/TopBar.js, src/css/application.css
For now, the hamburger icon will open the dashboard. Once the dashboard is gone, the hamburger menu will do other things.
Step 2 of #779
=> Add hamburger icon

src/createApplicationStore.js
Builds support for the excellent [Redux DevTools Extension](https://github.com/zalmoxisus/redux-devtools-extension).  Doesn’t do anything if the extension isn’t installed.
=> Support for Redux devtools

src/containers/TopBar.js
Was passing function reference rather than calling the function.
Fixes #968
=> Fix hamburger action dispatch

.travis.yml, package.json
New yarn version came out yesterday!
Also updated node to 8.4.0.
=> Upgrade yarn to 1.0.1

package.json, src/validations/html/htmllint.js, yarn.lock
Reverts popcodeorg/popcode#1062
Opening this branch for investigation, no idea what the fix is yet.
=> Bring back latest htmllint

webpack.config.js, yarn.lock
A couple of late-breaking ones since my initial PR. Upgrades `moment` and `webpack`.
=> More semver upgrades

yarn.lock
Upgrades all dependencies to latest semver compatible
=> Semver upgrade

package.json, yarn.lock
=> Upgrades inline-chunk-manifest-html-webpack-plugin

src/css/application.css
This PR subtly changes the color of the code labels so that it's clearer to differentiate them between the background color of the "current line" in the code. Also updated the "preview bar" to match for for general consistency.
=> Change color or labels and preview bar

locales/en/translation.json
=> remove example text from img src error

src/css/application.css
Fixes issue where unnecessary scrollbar shows up even when there's not enough content. Still maintains the ability to scroll once there is.
Fixes this issue: https://github.com/popcodeorg/popcode/issues/1207
=> Added styles to fix unnecessary extra scrolling issues.

src/css/application.css
Fixes issue https://github.com/popcodeorg/popcode/issues/1209
Trying to find another way to fix the double-scrollbar.
=> Removed overflow hidden.

src/components/TopBar/index.jsx, src/components/Workspace.jsx
Hello, I rename two `<div>`s as `<header>` and `<main>`. Issue #1200
=> Html5 semantics

src/validations/html/slowparse.js, yarn.lock
Upgrades dependencies to their latest compatible version with existing version specifications in package.json
=> Update semver dependencies

package.json, yarn.lock
Finally got an npm release for the recent improvements
=> Upgrade htmllint

src/components/Console.jsx, src/components/ConsoleInput.jsx, src/containers/Console.js, src/css/application.css, src/util/ace.js
Clicking the zoom button makes both the console input and output zoom in as well.
Closes #1288
=> Console respects zoom button

.eslintrc, src/actions/console.js, src/actions/index.js, src/components/Console.jsx, src/containers/Console.js, src/css/application.css, src/reducers/console.js
Had some fun on my train ride out to AOIT. Below does a first step towards clearing console. It's in the Backlog but it was so appetizing I couldn't resist. 
Questions...
1. Is it important to keep track of console history? ie should we remove the records completely or just move the entries up out of view ala terminal clear. 
2. Not sure if stopping the propagation is the correct way to block the click through.
3. Is circle with a line through the right type of button to have. I was mimicking the chrome console but not sure if this is the best for students. 
Notes
1. I'm waiting on the console.log() implementation to figure out console.clear() and command L.
=> add clear button to console

src/components/Console.jsx, src/containers/Console.js
Implementation copied from the <Preview/> component and its
associated container.
Fixes #1270
=> Hides the <Console/> if the project has errors

src/reducers/console.js
=> Fix enter in empty console to move into next line.

src/components/Console.jsx, src/containers/Console.js
The console is pretty solid at this point! This pull request makes it visible by default, regardless of experimental mode.
Closes #1285
=> Take console out of experimental mode

src/containers/Console.js, src/reducers/ui.js
=> Fix console input focus on input clearing.

yarn.lock
=> Remove artifacts in `yarn.lock`

package.json, yarn.lock
Upgrades to 0.16.0. Still seems to work fine
=> Upgrade bundlesize

package.json, yarn.lock
[Roan’s changes](https://github.com/fidian/PrettyCSS/pull/53) are in the latest release, so we can use it.
=> Upgrade PrettyCSS to latest

Dockerfile, README.md, docker-compose.yml
I have now embraced the all-Docker lifestyle. Setting this up for myself and anyone else who finds it convenient.
=> Simple Docker development setup

Dockerfile, docker-compose.yml, karma.conf.js, package.json, yarn.lock
* Install dependencies as part of Docker build
* Working tests in Docker environment
* Use a tmpfs for dist directory
=> Docker environment improvements

docker-compose.yml, gulpfile.js, package.json, webpack.config.js, yarn.lock
* Pass DEBUG environment variable to Docker container
* Fix output of Webpack errors
* Add Webpack Bundle Analyzer plugin
* Remove no-longer-used environment variable from env defaults
=> Omnibus dev tooling improvements

README.md, src/css/application.css
=> Releaser test

README.md
Reverts popcodeorg/popcode#1467
=> Revert "Releaser test"

README.md
Opening this up to verify I have permissions to merge PRs and revert.
=> Bespoke README change

README.md
This reverts commit efdc151951efcfa7f1d098531ecd5ec99283b435, reversing
changes made to 2911da0db8fdd37fba6e9b52822f094cbb3d1298.
=> Revert "Merge pull request #1470 from alex/bespoke-readme-change

src/static/privacy.html
=> Privacy policy

.travis.yml, docker-compose.yml
Adds the Travis Slack integration for easier monitoring of build and release status.
Also sets up a Docker container for the Travis CLI.
=> Add Travis Slack integration

src/components/TopBar/ExportMenu.jsx, src/components/TopBar/ExportMenuButton.jsx, src/components/TopBar/HamburgerMenu.jsx, src/components/TopBar/createMenu.jsx, src/components/TopBar/index.jsx, src/css/application.css
From the Export Repo Project Board.
Moved all export functionality to dropdown next to the snapshot button. 
Fixes #1480
=> add export under snapshot

yarn.lock
Nothing notable changed, just bumping up to latest
=> Upgrade eslint_d and eslint_plugin_promise

yarn.lock
Changes to webpack look to be mostly irrelevant / webassembly-related; offline-plugin is just a patchlevel; webpack-bundle-analyzer changes are also fairly uninteresting.
=> Upgrade webpack, webpack-bundle-analyzer, offline-plugin

yarn.lock
* `sweetalert2`
* `sinon`
* `redux-saga-test-plan`
* `bugsnag-js`
None have particularly interesting changes.
=> Several minor version dependency upgrades

src/css/application.css
=> remove hidden from top-bar__project-saved

src/components/TopBar/CurrentUser.jsx, src/components/TopBar/HamburgerMenu.jsx, src/components/TopBar/index.jsx
Instead of having a separate Google login button in the hamburger menu, just make the main login button log you in to Google in experimental mode.
Closes #1515
=> Default to Google login in experimental mode

src/sagas/user.js, test/unit/sagas/user.js
Removes check for experimental mode when deciding whether to propose an account merge.
=> Account merge wide release

src/clients/github.js
Start with the page title, then increment and append a number to the
page title on failure. Before we used timestamp to guarantee unique
names but this creates shorter and more easily shareable names.
Fixes: #1476
=> Add backoff/retry logic to generate more intuitive repo export names

.travis.yml, docker-compose.yml
* Use latest release build as cache source for development Docker build as well
* Pass missing `FIREBASE_APP` environment variable to `syncFirebase` task
=> More Docker build improvements

package-lock.json, package.json, src/sagas/ui.js, src/sagas/user.js, test/unit/sagas/clients.js, test/unit/sagas/errors.js, test/unit/sagas/manageUserState.js, test/unit/sagas/projects.js, test/unit/sagas/ui.js, test/unit/sagas/user.js
Delay and debounce are now effects.
This upgrade is waiting on jfairbank/redux-saga-test-plan#242 to be merged
=> Upgrade redux-saga and redux-saga-test-plan to 1.0.1

locales/en/translation.json, src/actions/index.js, src/actions/user.js, src/clients/firebase.js, src/components/TopBar/CurrentUser.jsx, src/components/TopBar/CurrentUserMenu.jsx, src/components/TopBar/index.jsx, src/containers/TopBar.js, src/records/UserIdentityProvider.js, src/reducers/ui.js, src/reducers/user.js, src/sagas/user.js, test/helpers/Scenario.js, test/helpers/factory.js, test/unit/reducers/projects.js, test/unit/reducers/ui.js, test/unit/reducers/user.js, test/unit/sagas/user.js
Adds a menu option in the user drop-down to unlink the linked GitHub account, if there is one:
=> [WIP] Unlink GitHub

src/services/gapi.js
We've been seeing a lot of errors (both user reports and automated error monitoring) in which the `gapi` script fails to load. Previously we were using `loadjs`'s built-in retry logic, but this does not do exponential
backoff so will not behave well in a brief network outage. Instead just use `promiseRetry` like we do everywhere else.
Fixes #1665
=> Use promiseRetry to retry gapi load

babel.config.js, webpack.config.js
Reverts popcodeorg/popcode#1674
=> Revert "Run all node_modules through babel"

README.md, package.json
Also added Shen to `package.json` since he was missing from there
Also fixes `keywords` in `package.json` while I’m in there.
=> Add Maggie to contribs

src/components/PreviewFrame.jsx
I changed the logic for calculating the line number of error messages in #1692, but did not consider a case where the error message could actually come from one of the libraries we are using. The smallest reproduction steps for this are:
1. Turn on p5.js in the list of libraries
2. Write some code like this:
```javascript
function setup(){
createCanvas(500, 500); 
}
function draw() {
fill();
}
```
Before, this would throw an additional error from sourcemapping. Now, it shows the following error:
```
On line 1:
[object Arguments]is not a valid color representation.
```
In Safari, we don't have access to the line number, so it always shows:
```
On line 1:
Script error.
```
That behavior is unchanged.
=> Better handling of errors in library code

README.md, contrib/vscode/tasks.json
Streamlines certain parts, updates to match current status, and most importantly the default instructions for setting up the development environment are to use the One True Development Environment.
=> README updates

locales/en/translation.json, src/validations/html/rules/index.js, src/validations/html/slowparse.js, src/validations/mergeValidations.js
=> Missing closing title tag generates validation error

.renovaterc.json
#1873 only contained a subset of the changes I intended, and also did not work. Trying again.
=> Renovate concurrency, again

README.md, package.json
Add @joshling1919 to contributor lists
=> Add Joshua to list of contributors

build/build.sh
I forget to do this every time!!!
=> Add Mixpanel Token to environment variables in build

src/reducers/ui.js
Refactors UI reducer, making two major changes:
* Uses `handleActions` to define each action handler, which is the goal for all reducers
* Uses `combineReducers` internally to further subdivide the UI reducer into reducers for each top-level property. This seems sensible to me because the UI reducer is essentially a collection of more-or-less unrelated properties all of which happen to relate to UI state rather than underlying data state. The reducer is also _huge_ and was pretty haphazardly organized; grouping the logic for each individual UI property helps keep related things together in the code.
=> Refactor UI reducer

src/reducers/__tests__/ui.test.js, src/reducers/ui.js
Fixes uncaught error when copy snapshot link is pressed.
=> fix: Fix updateNotificationMetadata handler

src/components/Modal.jsx, src/components/ProjectPickerModal.jsx, src/components/ProjectPreview.jsx, src/components/TopBar/ProjectPickerButton.jsx, src/css/application.css, src/reducers/__tests__/ui.test.js, src/selectors/getAllProjects.js
Addresses issue #2099 Fast follows for project picker modal
=> Project picker fast follow

src/components/PreviewFrame.jsx, src/html/preview.html, src/preview.js, src/previewSupport/handleSourceUpdates.js, src/util/compileProject.js, webpack.config.js
Reverts popcodeorg/popcode#2107. This pull request breaks console interaction as discussed in #2149. The underlying cause of the breakage is tractable in principle, but will require some research into how best to accomplish it.
=> Revert "Secure preview frame"

locales/en/translation.json, src/components/TopBar/HamburgerMenu.jsx, src/components/TopBar/index.jsx, src/components/__tests__/HamburgerMenu.test.jsx, src/containers/TopBar.js
This PR adds a button to the hamburger menu to format code.
=> Adds button to hamburger menu to format code

src/components/Editor.jsx
Adds support to the editor to be able to block comment code.
Kept the original commit from @thayerve so they get credit.
=> Adds support for Ctrl-/ block commenting

yarn.lock
Meant to push this to #2372 before merging
=> Manually deduplicate yarn.lock
